// ============================================================================
// scripts-longform — 롱폼(8분) 대본
// ----------------------------------------------------------------------------
// ⛔ 왜 파일을 나누는가
//   쇼츠 대본(scripts.ts)과 규칙이 다르다. 길이창도, 비트 수도, 게이트도 다르다.
//   한 파일에 두면 쇼츠 게이트가 롱폼을 자르거나 롱폼 규칙이 쇼츠를 오염시킨다.
//
// ★ 이 편의 설계 근거 — 전부 .agent/LONGFORM_RESEARCH.md 의 실측
//   길이   8분 (대표 지시) — 미국 롱폼 8~12분 구간 조회중앙 48,915 · 검증 구간 안
//   제목   「~ Is Worse Than You Think」 = 채널크기 통제 후 1.57배 (측정된 최강 장치)
//          ⛔ 「Explained」(0.88x) · 「Nobody / Secret」(0.86x) 는 쓰지 않는다
//   소재   시장 사건 계급 = 1.45배 (1위)
//   뼈대   한국 레퍼런스: 콜드 오픈 → 인사 0:35 → 목차를 «개수»로 → 중간 반전
//          → 예외 → 리스크 → 「볼 것 3개」 → 면책
//   리듬   재훅 분당 0.58~0.59 · 물음표 분당 1.4 (두 레퍼런스가 수렴한 값)
//   우리 색  대리인 캐릭터(Charlie) 자리에 «표본»을 넣는다 — 228번을 따라간다
//
// ★ 데이터 — scripts/edge-earnings.mjs 사전등록 후 계산. 원본 .agent/_edge_earnings.json
//   10종목(NVDA AMD MU AVGO AAPL MSFT GOOGL AMZN META TSLA) 2021-01-01~2026-08-20
//   실적 다음 거래일 종가 수익률 228회
//   폭:   절대수익 6.39% vs 평상 1.85% = 3.45배 · 10/10 종목 · 부호검정 p=0.00195
//   방향: 상승 108/228 = 47.4% · z=-0.79 → 동전과 구분되지 않는다
//   NVDA: 22회 · 6.20% vs 2.31% = 2.69배 · 상승 11/22 = «정확히» 50.0%
//   AVGO: 상승 16/22 = 72.7% (유일하게 한쪽으로 치우친 종목)
//   META: 6.11배 (가장 넓다) · AAPL: 2.39배 (가장 좁다)
//
// ⛔ 「방향은 랜덤이다」로 쓰지 않는다. z=-0.79 는 «동전과 구분되지 않는다»이지
//   «랜덤임이 증명됐다»가 아니다. 말할 수 있는 것은 「아무도 못 맞혔다」까지다.
// ⛔ 매수·매도 권유 금지. 위치와 분포만 보여준다.
// ============================================================================
import type { BriefingProps } from './Briefing';
import { VOICE_LFEARN } from './voice-lfearn';

const V = (src: string) =>
  ({ kind: 'video', src: `shorts/bg/video/${src}`, loopFrames: 150 }) as const;

export const SCRIPT_LFEARN: BriefingProps = {
  title: 'The earnings trade is\nworse than you think.',
  date: 'AUG 26 · EARNINGS',
  longform: true,
  slowCuts: true,
  noOutro: true,

  hook: {
    line: 'Everyone calls\nthe direction.',
    sub: 'We counted 228 of them.',
    say: 'Hold on. Nobody has called the direction.',
    role: 'conflict',
    syms: ['NVDA'],
    bg: V('pcb-traces-glow.mp4'),
  },
  loop: 'The size is knowable.\nThe direction is not.',

  chapters: [
    { at: 0, no: '01', title: 'THE RITUAL' },
    { at: 6, no: '02', title: 'WHAT WE COUNTED' },
    { at: 13, no: '03', title: 'THE SIZE IS REAL' },
    { at: 21, no: '04', title: 'THE DIRECTION IS NOT' },
    { at: 29, no: '05', title: 'THE EXCEPTIONS' },
    { at: 36, no: '06', title: 'WHAT THIS DOES NOT SAY' },
    { at: 40, no: '07', title: 'THREE NUMBERS' },
  ],

  beats: [
    // ── 01 THE RITUAL ────────────────────────────────────────────────────────
    {
      role: 'conflict', prio: 1, bg: V('nyse-flags.mp4'),
      eyebrow: 'Every quarter',
      head: 'Nvidia reports\non Tuesday',
      say: 'Nvidia reports on Tuesday the twenty sixth.',
      ask: 'Consensus is two oh nine a share.',
      visual: { kind: 'rows', rows: [
        { k: 'Report date', v: 'Aug 26', up: true, note: 'confirmed on the earnings calendar' },
        { k: 'Consensus EPS', v: '$2.09', up: true, note: 'street estimate' },
        { k: 'Consensus revenue', v: '$92.0B', up: true, note: 'street estimate' },
      ] },
    },
    {
      role: 'conflict', prio: 1, bg: V('exchange-flags.mp4'),
      eyebrow: 'The ritual',
      head: 'Everyone picks\na direction',
      say: 'By Monday every desk will have picked a side.',
      ask: 'Up or down. That is the whole conversation.',
      visual: { kind: 'stat', label: 'THE QUESTION EVERYONE ASKS', value: 'UP OR DOWN',
        sub: 'repeated every quarter for years', up: false },
    },
    {
      role: 'conflict', prio: 1, bg: V('desks-dawn.mp4'),
      eyebrow: 'Nobody checks',
      head: 'And nobody\nkeeps score',
      say: 'What nobody does is keep score afterwards.',
      ask: 'So we did. Every print since twenty twenty one.',
      visual: { kind: 'stat', label: 'WHAT IS MISSING', value: 'THE SCORECARD',
        sub: 'the calls are made, then forgotten', up: false },
    },
    {
      role: 'conflict', prio: 1, bg: V('exchange-storm.mp4'),
      eyebrow: 'Who is talking',
      head: 'We run the\nnumbers first',
      say: 'This is SIGNUM. We count things before we talk about them.',
      ask: 'Every number here comes with the sample size.',
      visual: { kind: 'stat', label: 'HOW WE WORK', value: 'COUNT FIRST',
        sub: 'the test is fixed before the data is pulled', up: true },
    },
    {
      role: 'conflict', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'What you will get',
      head: 'Three things,\nthen one number',
      say: 'Three things today, then one number you can check.',
      ask: 'First, what earnings actually do to a stock.',
      visual: { kind: 'rows', rows: [
        { k: 'One', v: 'The size', up: true, note: 'how far it moves' },
        { k: 'Two', v: 'The direction', up: false, note: 'which way it goes' },
        { k: 'Three', v: 'The exceptions', up: true, note: 'the names that break the rule' },
      ] },
    },
    {
      role: 'conflict', prio: 1, bg: V('golden-bell.mp4'),
      eyebrow: 'The setup',
      head: 'Two questions,\nnot one',
      say: 'There are two questions hiding inside that one.',
      ask: 'How far does it move, and which way.',
      visual: { kind: 'versus', aK: 'How far', aV: 'SIZE', bK: 'Which way', bV: 'DIRECTION' },
    },
    {
      role: 'conflict', prio: 1, bg: V('scale-few-vs-many.mp4'),
      eyebrow: 'Spoiler',
      head: 'One is knowable.\nOne is not',
      say: 'One of them is knowable. The other one is not.',
      ask: 'The market prices both as if they were the same.',
      visual: { kind: 'stat', label: 'THE SPLIT', value: 'ONE OF TWO',
        sub: 'and the tradeable half is not the one you think', up: false },
    },

    {
      role: 'evidence', prio: 1, bg: V('geo-radar-dusk.mp4'),
      eyebrow: 'Think of it this way',
      head: 'A forecast tells you\nthe storm is severe',
      say: 'A weather service can tell you the storm will be severe.',
      ask: 'It cannot tell you which street the lightning hits.',
      visual: { kind: 'versus', aK: 'Forecastable', aV: 'SEVERITY', bK: 'Not forecastable', bV: 'THE STRIKE' },
    },
    {
      role: 'evidence', prio: 1, bg: V('temple-storm.mp4'),
      eyebrow: 'Same shape',
      head: 'Earnings are the\nsame shape',
      say: 'Earnings work the same way, and the market knows it.',
      ask: 'It sells you the severity and stays quiet on the strike.',
      visual: { kind: 'stat', label: 'WHAT IS SOLD TO YOU', value: 'SEVERITY', sub: 'the direction is not for sale because nobody has it', up: false },
    },
    // ── 02 WHAT WE COUNTED ───────────────────────────────────────────────────
    {
      role: 'evidence', prio: 1, bg: V('server-assembly.mp4'),
      eyebrow: 'The sample',
      head: 'Ten names.\nSix years',
      say: 'We took the ten largest names people actually trade.',
      ask: 'Nvidia, AMD, Micron, Broadcom, Apple.',
      visual: { kind: 'rows', rows: [
        { k: 'Semis', v: 'NVDA AMD MU AVGO', up: true, note: 'four chip names' },
        { k: 'Platforms', v: 'AAPL MSFT GOOGL', up: true, note: 'three' },
        { k: 'And', v: 'AMZN META TSLA', up: true, note: 'three more' },
      ] },
    },
    {
      role: 'evidence', prio: 1, bg: V('chip-city.mp4'),
      eyebrow: 'The window',
      head: 'January\ntwenty twenty one',
      say: 'Every earnings print since January twenty twenty one.',
      ask: 'That is two hundred and twenty eight of them.',
      visual: { kind: 'rows', rows: [
        { k: 'From', v: '2021-01-01', up: true, note: 'start of the window' },
        { k: 'To', v: '2026-08-20', up: true, note: 'last full session' },
        { k: 'Prints counted', v: '228', up: true, note: 'nothing dropped' },
      ] },
    },
    {
      role: 'evidence', prio: 1, bg: V('datacenter-aisle.mp4'),
      eyebrow: 'The measurement',
      head: 'Close to close,\nnext session',
      say: 'We measured the close to close move the session after.',
      ask: 'Not the after hours print. The session everyone trades.',
      visual: { kind: 'stat', label: 'WHAT WE MEASURED', value: 'NEXT CLOSE',
        sub: 'the day the whole market gets to react', up: true },
    },
    {
      role: 'evidence', prio: 1, bg: V('fed-building.mp4'),
      eyebrow: 'The control',
      head: 'Against every\nordinary day',
      say: 'We compared that to an ordinary day for the same name.',
      ask: 'Same window, every session, no cherry picking.',
      visual: { kind: 'versus', aK: 'Earnings day', aV: '228 prints', bK: 'Ordinary day', bV: 'all sessions' },
    },
    {
      role: 'evidence', prio: 1, bg: V('vault-doors.mp4'),
      eyebrow: 'Written down first',
      head: 'We fixed the test\nbefore we ran it',
      say: 'We wrote the test down before we ran it.',
      ask: 'Names, window, definition, statistic. All fixed.',
      visual: { kind: 'rows', rows: [
        { k: 'Fixed first', v: 'the names', up: true, note: 'no adding winners later' },
        { k: 'Fixed first', v: 'the window', up: true, note: 'no moving the start date' },
        { k: 'Fixed first', v: 'the test', up: true, note: 'Welch t and a binomial' },
      ] },
    },
    {
      role: 'evidence', prio: 1, bg: V('glass-tube-array.mp4'),
      eyebrow: 'Why that matters',
      head: 'You can move\nany number',
      say: 'Any number moves if you choose the window afterwards.',
      ask: 'So the window is the first thing you give up.',
      visual: { kind: 'stat', label: 'THE RULE WE PUT ON OURSELVES', value: 'DECIDE FIRST',
        sub: 'the sample cannot be edited by the result', up: true },
    },
    {
      role: 'evidence', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'Now the answer',
      head: 'Two hundred\ntwenty eight',
      say: 'Two hundred and twenty eight prints. Here is what came back.',
      ask: 'Start with how far the stock moved.',
      visual: { kind: 'stat', label: 'SAMPLE', value: '228',
        sub: 'ten names, six years, nothing dropped', up: true },
    },

    {
      role: 'evidence', prio: 1, bg: V('desks-dawn.mp4'),
      eyebrow: 'One word first',
      head: 'What a consensus\nactually is',
      say: 'One word first, because everything hangs on it. Consensus.',
      ask: 'It is just the average of the analysts who publish a number.',
      visual: { kind: 'stat', label: 'CONSENSUS', value: 'AN AVERAGE', sub: 'of the analysts who chose to publish', up: true },
    },
    {
      role: 'evidence', prio: 1, bg: V('paper-crowd.mp4'),
      eyebrow: 'Not a prophecy',
      head: 'It is a poll,\nnot a forecast',
      say: 'It is closer to a poll than to a prediction.',
      ask: 'And the stock has already been bought at that poll.',
      visual: { kind: 'versus', aK: 'People think', aV: 'A FORECAST', bK: 'It is', bV: 'A POLL' },
    },
    {
      role: 'evidence', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'So a beat is not a beat',
      head: 'Beating it is\nnot the same as good',
      say: 'So beating the consensus is not the same as being good.',
      ask: 'It only means the poll was set a little low.',
      visual: { kind: 'stat', label: 'WHAT A BEAT MEANS', value: 'THE POLL WAS LOW', sub: 'not that the quarter was strong in itself', up: false },
    },
    {
      role: 'evidence', prio: 1, bg: V('glass-tube-array.mp4'),
      eyebrow: 'And that is why',
      head: 'Two companies,\nsame beat',
      say: 'Two companies can beat by the same amount and move opposite ways.',
      ask: 'We have that in the sample more than once.',
      visual: { kind: 'stat', label: 'SAME BEAT, OPPOSITE CLOSE', value: 'IT HAPPENS', sub: 'because the bar was in a different place', up: false },
    },
    // ── 03 THE SIZE IS REAL ──────────────────────────────────────────────────
    {
      role: 'money', prio: 1, bg: V('euv-plasma-a.mp4'),
      eyebrow: 'The size',
      head: 'Six point three\nnine percent',
      say: 'The day after earnings averages six point four percent.',
      ask: 'That is the absolute move, up or down.',
      visual: { kind: 'stat', label: 'AVERAGE ABSOLUTE MOVE - EARNINGS DAY', value: '6.39%',
        sub: '228 prints', up: true },
    },
    {
      role: 'money', prio: 1, bg: V('calm-sea-dawn.mp4'),
      eyebrow: 'An ordinary day',
      head: 'One point\neight five',
      say: 'An ordinary day for the same names is one point eight five.',
      ask: 'Same stocks. Same years. Very different day.',
      visual: { kind: 'versus', aK: 'Ordinary day', aV: '1.85%', bK: 'Earnings day', bV: '6.39%' },
    },
    {
      role: 'money', prio: 1, bg: V('steel-spheres.mp4'),
      eyebrow: 'The multiple',
      head: 'Three and a half\ntimes',
      say: 'Three point four five times a normal day.',
      ask: 'That is not a small edge. That is a different animal.',
      visual: { kind: 'stat', label: 'EARNINGS DAY vs ORDINARY DAY', value: '3.45x',
        sub: 'the size is not subtle', up: true },
    },
    {
      role: 'money', prio: 1, bg: V('columns-goldenhour.mp4'),
      eyebrow: 'How consistent',
      head: 'All ten names.\nNo exceptions',
      say: 'Every single one of the ten names showed it.',
      ask: 'Ten out of ten, in the same direction.',
      visual: { kind: 'rows', rows: [
        { k: 'Names wider on earnings', v: '10 / 10', up: true, note: 'no counterexample' },
        { k: 'Sign test', v: 'p = 0.002', up: true, note: 'two sided' },
        { k: 'Per-name t', v: '3.10 - 5.85', up: true, note: 'all significant' },
      ] },
    },
    {
      role: 'money', prio: 1, bg: V('wafer-spin-clean.mp4'),
      eyebrow: 'The widest',
      head: 'Meta moves\nsix times',
      say: 'Meta is the widest. Six point one times its normal day.',
      ask: 'Ten percent on average, the day after.',
      visual: { kind: 'rows', rows: [
        { k: 'META earnings day', v: '10.09%', up: true, note: 'the widest of the ten' },
        { k: 'META ordinary day', v: '1.65%', up: false, note: 'unusually calm otherwise' },
        { k: 'Multiple', v: '6.11x', up: true, note: 'the biggest gap in the set' },
      ] },
    },
    {
      role: 'money', prio: 1, bg: V('device-assembly-bright.mp4'),
      eyebrow: 'The narrowest',
      head: 'Apple moves\ntwo point four',
      say: 'Apple is the calmest, and it still doubles.',
      ask: 'Even the quiet one is not quiet that day.',
      visual: { kind: 'rows', rows: [
        { k: 'AAPL earnings day', v: '2.93%', up: true, note: 'smallest absolute move' },
        { k: 'AAPL ordinary day', v: '1.22%', up: false, note: 'also the calmest normally' },
        { k: 'Multiple', v: '2.39x', up: true, note: 'still more than double' },
      ] },
    },
    {
      role: 'money', prio: 1, bg: V('mirror-city.mp4'),
      eyebrow: 'So far so good',
      head: 'The size part\nis solid',
      say: 'So the size holds up. It is measurable and it repeats.',
      ask: 'But here is where it breaks.',
      visual: { kind: 'stat', label: 'HALF THE QUESTION - ANSWERED', value: 'SIZE',
        sub: 'consistent across ten names and six years', up: true },
    },
    {
      role: 'money', prio: 1, bg: V('crack-star.mp4'),
      eyebrow: 'The turn',
      head: 'Now the half\nthat pays',
      say: 'Because knowing how far it moves does not pay you.',
      ask: 'Only knowing which way does.',
      visual: { kind: 'versus', aK: 'What we proved', aV: 'HOW FAR', bK: 'What pays', bV: 'WHICH WAY' },
    },

    {
      role: 'evidence', prio: 1, bg: V('steel-balls.mp4'),
      eyebrow: 'A second way to see it',
      head: 'You can flip a coin\nharder',
      say: 'You can flip a coin harder. It travels further and spins more.',
      ask: 'It still lands heads about half the time.',
      visual: { kind: 'stat', label: 'HARDER IS NOT MORE PREDICTABLE', value: 'STILL 50/50', sub: 'force changes the size of the flip, not the odds', up: false },
    },
    {
      role: 'evidence', prio: 1, bg: V('wafer-press.mp4'),
      eyebrow: 'That is earnings',
      head: 'Earnings flip the\ncoin harder',
      say: 'An earnings print flips the coin harder. That is all it does.',
      ask: 'Three and a half times harder, to be exact.',
      visual: { kind: 'versus', aK: 'Ordinary flip', aV: '1.85%', bK: 'Earnings flip', bV: '6.39%' },
    },
    {
      role: 'evidence', prio: 1, bg: V('wafer-arm.mp4'),
      eyebrow: 'Two more names',
      head: 'Amazon four times.\nMicrosoft four',
      say: 'Amazon runs four point four times its ordinary day.',
      ask: 'Microsoft, three point nine. Google, three point eight.',
      visual: { kind: 'rows', rows: [{ k: 'AMZN', v: '4.43x', up: true, note: '6.65% vs 1.50%' },{ k: 'MSFT', v: '3.92x', up: true, note: '4.60% vs 1.17%' },{ k: 'GOOGL', v: '3.81x', up: true, note: '5.23% vs 1.37%' } ] },
    },
    {
      role: 'evidence', prio: 1, bg: V('geo-refinery-day.mp4'),
      eyebrow: 'Even the volatile ones',
      head: 'Tesla three times.\nMicron two point eight',
      say: 'Tesla is already a wild stock and it still triples.',
      ask: 'Micron, AMD, Nvidia all sit near two point seven.',
      visual: { kind: 'rows', rows: [{ k: 'TSLA', v: '3.00x', up: true, note: '7.94% vs 2.64% - already volatile' },{ k: 'MU', v: '2.75x', up: true, note: '6.67% vs 2.42%' },{ k: 'AMD', v: '2.80x', up: true, note: '6.86% vs 2.45%' } ] },
    },
    {
      role: 'money', prio: 1, bg: V('fiber-one-lit.mp4'),
      eyebrow: 'There is a price for it',
      head: 'The market sells\nthe size',
      say: 'Here is the part most people never look at.',
      ask: 'The options market publishes a price for the size.',
      visual: { kind: 'stat', label: 'THE IMPLIED MOVE', value: 'PUBLISHED', sub: 'the market quotes how far it expects the stock to go', up: true },
    },
    {
      role: 'money', prio: 1, bg: V('gold-bars.mp4'),
      eyebrow: 'Like an insurance quote',
      head: 'It reads like\nan insurance premium',
      say: 'Read it like an insurance premium on a house.',
      ask: 'The premium tells you the risk. It does not tell you the fire.',
      visual: { kind: 'versus', aK: 'The premium says', aV: 'HOW BIG', bK: 'It never says', bV: 'IF IT BURNS' },
    },
    {
      role: 'money', prio: 1, bg: V('vault-doors.mp4'),
      eyebrow: 'So the edge is not there',
      head: 'If it is priced,\nit is not free',
      say: 'If the size is already priced, buying the size is not free money.',
      ask: 'You are paying a premium for a move you already expect.',
      visual: { kind: 'stat', label: 'WHY 3.45x IS NOT AN EDGE BY ITSELF', value: 'IT IS PRICED', sub: 'the expected move is in what you pay', up: false },
    },
    {
      role: 'money', prio: 1, bg: V('steel-spheres.mp4'),
      eyebrow: 'What the count is for',
      head: 'The count tells you\nwhat normal is',
      say: 'What the count gives you is a definition of normal.',
      ask: 'Six point two for Nvidia. That is the yardstick.',
      visual: { kind: 'stat', label: 'WHAT YOU GET FROM 228 PRINTS', value: 'A YARDSTICK', sub: 'a number to compare Wednesday against', up: true },
    },
    // ── 04 THE DIRECTION IS NOT ──────────────────────────────────────────────
    {
      role: 'verdict', prio: 1, bg: V('scale-few-vs-many.mp4'),
      eyebrow: 'The direction',
      head: 'One hundred\nand eight',
      say: 'Of those two hundred twenty eight prints, one oh eight closed higher.',
      ask: 'Count them yourself. It is a public number.',
      visual: { kind: 'rows', rows: [
        { k: 'Closed higher', v: '108', up: true, note: 'of 228' },
        { k: 'Closed lower', v: '120', up: false, note: 'the rest' },
        { k: 'Share up', v: '47.4%', up: false, note: 'slightly under half' },
      ] },
    },
    {
      role: 'verdict', prio: 1, bg: V('steel-balls.mp4'),
      eyebrow: 'That is',
      head: 'Forty seven\npoint four',
      say: 'Forty seven point four percent.',
      ask: 'A coin lands at fifty. This landed at forty seven.',
      visual: { kind: 'stat', label: 'WENT UP - 108 OF 228', value: '47.4%',
        sub: 'a coin would give you 50', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('undercurrent-pull.mp4'),
      eyebrow: 'Is that different',
      head: 'z equals\nminus zero point eight',
      say: 'The distance from a coin is minus zero point seven nine.',
      ask: 'In plain words, we cannot tell it apart from a coin.',
      visual: { kind: 'stat', label: 'DISTANCE FROM A COIN FLIP', value: 'z = -0.79',
        sub: 'not distinguishable at any usual threshold', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('paper-crowd.mp4'),
      eyebrow: 'Read it carefully',
      head: 'Not proof\nof randomness',
      say: 'That is not the same as proving it is random.',
      ask: 'It means nobody in this sample beat a coin.',
      visual: { kind: 'stat', label: 'WHAT THE NUMBER SAYS', value: 'NOBODY BEAT IT',
        sub: 'we did not prove randomness - we failed to find skill', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('floor-empty-night.mp4'),
      eyebrow: 'Why it happens',
      head: 'The estimate is\nalready in the price',
      say: 'The reason is that the estimate is already in the price.',
      ask: 'What moves the stock is the surprise, not the result.',
      visual: { kind: 'versus', aK: 'Already priced', aV: 'THE ESTIMATE', bK: 'Moves it', bV: 'THE SURPRISE' },
    },
    {
      role: 'verdict', prio: 1, bg: V('rams-vs-block.mp4'),
      eyebrow: 'And so',
      head: 'The size grows.\nThe sign does not',
      say: 'A surprise has a size and a sign.',
      ask: 'Options price the size. Nothing prices the sign.',
      visual: { kind: 'rows', rows: [
        { k: 'Size of surprise', v: 'PRICED', up: true, note: 'the options market does this well' },
        { k: 'Sign of surprise', v: 'NOT PRICED', up: false, note: 'nothing can - it is not known' },
        { k: 'Result', v: '3.45x / 47.4%', up: false, note: 'wide, and a coin flip' },
      ] },
    },
    {
      role: 'verdict', prio: 1, bg: V('floor-empty-night.mp4'),
      eyebrow: 'A fair question',
      head: 'So just buy\nthe move?',
      say: 'So can you just buy the move and ignore direction?',
      ask: 'That is the right question, and the answer is no.',
      visual: { kind: 'stat', label: 'THE OBVIOUS NEXT QUESTION', value: 'BUY THE MOVE?',
        sub: 'the size is priced too - you pay for it up front', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('glass-tube-array.mp4'),
      eyebrow: 'The consequence',
      head: 'Good results,\nlower close',
      say: 'This is why a great quarter can still close red.',
      ask: 'The bar was already raised before the print.',
      visual: { kind: 'stat', label: 'WHY GOOD NEWS CAN CLOSE LOWER', value: 'THE BAR MOVED',
        sub: 'you are being scored against expectations', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'Half and half',
      head: 'One side of the\ntrade is real',
      say: 'So one half of this trade is real and one half is not.',
      ask: 'Now look at the names that break even that.',
      visual: { kind: 'versus', aK: 'Size', aV: 'REAL', bK: 'Direction', bV: 'A COIN' },
    },

    {
      role: 'evidence', prio: 1, bg: V('rise-stairs-light.mp4'),
      eyebrow: 'Here is why',
      head: 'Think of a high\njump bar',
      say: 'Picture a high jump. The company has to clear a bar.',
      ask: 'The bar is not the last quarter. It is what people expect now.',
      visual: { kind: 'versus', aK: 'Not the bar', aV: 'LAST QUARTER', bK: 'The bar', bV: 'EXPECTATIONS' },
    },
    {
      role: 'evidence', prio: 1, bg: V('rise-glass-tower.mp4'),
      eyebrow: 'And the bar moves',
      head: 'Every good quarter\nraises it',
      say: 'Every quarter they clear, someone raises the bar.',
      ask: 'So a great result can still be a miss against the bar.',
      visual: { kind: 'stat', label: 'WHY BEATING LAST QUARTER IS NOT ENOUGH', value: 'THE BAR RISES', sub: 'you are scored against expectation, not history', up: false },
    },
    {
      role: 'evidence', prio: 1, bg: V('gold-bars.mp4'),
      eyebrow: 'A third way to see it',
      head: 'It works like\nan auction',
      say: 'It also works like an auction that closed before the print.',
      ask: 'Everyone already bid what they thought the number would be.',
      visual: { kind: 'stat', label: 'WHEN THE BIDDING HAPPENED', value: 'BEFORE', sub: 'the price you see already contains the guess', up: false },
    },
    {
      role: 'evidence', prio: 1, bg: V('steel-spheres.mp4'),
      eyebrow: 'So what is left',
      head: 'Only the part nobody\nguessed',
      say: 'What is left to move the stock is the part nobody guessed.',
      ask: 'And nobody knows the sign of a thing nobody guessed.',
      visual: { kind: 'versus', aK: 'Already in the price', aV: 'THE GUESS', bK: 'Moves the stock', bV: 'THE MISS' },
    },
    {
      role: 'evidence', prio: 1, bg: V('fiber-one-lit.mp4'),
      eyebrow: 'Which is why',
      head: 'The options market\nprices one side',
      say: 'The options market is good at the size and silent on the sign.',
      ask: 'That is not a failure. It is the honest answer.',
      visual: { kind: 'rows', rows: [{ k: 'Options can price', v: 'SIZE', up: true, note: 'and they do it well' },{ k: 'Options cannot price', v: 'SIGN', up: false, note: 'nothing can' },{ k: 'Our count agrees', v: '47.4%', up: false, note: '108 of 228' } ] },
    },
    {
      role: 'verdict', prio: 1, bg: V('chip-city.mp4'),
      eyebrow: 'Look at the record',
      head: 'Nvidia has printed\ntwenty two times',
      say: 'Nvidia has printed twenty two times inside our window.',
      ask: 'Eleven of those closed green. Eleven closed red.',
      visual: { kind: 'rows', rows: [{ k: 'Green closes', v: '11', up: true, note: 'the day after the print' }, { k: 'Red closes', v: '11', up: false, note: 'the same count' }, { k: 'Split', v: '50.0%', up: false, note: 'a literal even split' }] },
    },
    {
      role: 'verdict', prio: 1, bg: V('datacenter-aisle.mp4'),
      eyebrow: 'Through everything',
      head: 'Through the boom\nand the drawdown',
      say: 'That split held through the boom and through the drawdown.',
      ask: 'The story changed completely. The coin did not.',
      visual: { kind: 'stat', label: 'ACROSS SIX YEARS OF REGIME CHANGE', value: 'STILL 50/50', sub: 'the narrative moved - the split did not', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('crack-star.mp4'),
      eyebrow: 'The uncomfortable part',
      head: 'A great quarter\ncan still close red',
      say: 'Which means a great quarter can still close red.',
      ask: 'Not a glitch. That is the mechanism doing its job.',
      visual: { kind: 'stat', label: 'THIS IS NOT A GLITCH', value: 'THE MECHANISM', sub: 'expectation is the thing being traded', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('undercurrent-pull.mp4'),
      eyebrow: 'And the reverse',
      head: 'A weak quarter\ncan close green',
      say: 'And a weak quarter can close green, for the same reason.',
      ask: 'The bar was low enough that missing it was survivable.',
      visual: { kind: 'versus', aK: 'Good result', aV: 'CAN FALL', bK: 'Weak result', bV: 'CAN RISE' },
    },
    // ── 05 THE EXCEPTIONS ────────────────────────────────────────────────────
    {
      role: 'chips', prio: 1, bg: V('pcb-one-chip-lit.mp4'),
      eyebrow: 'Nvidia itself',
      head: 'Eleven up.\nEleven down',
      say: 'Nvidia landed on exactly half. Eleven and eleven.',
      ask: 'Twenty two prints, split down the middle.',
      visual: { kind: 'rows', rows: [
        { k: 'NVDA prints', v: '22', up: true, note: 'since 2021' },
        { k: 'Closed higher', v: '11', up: true, note: 'exactly half' },
        { k: 'Share up', v: '50.0%', up: false, note: 'a literal coin' },
      ] },
    },
    {
      role: 'chips', prio: 1, bg: V('chip-macro-grey.mp4'),
      eyebrow: 'But the size',
      head: 'Two point\nsix nine times',
      say: 'Its size is still there. Two point six nine times.',
      ask: 'From two point three percent to six point two.',
      visual: { kind: 'rows', rows: [
        { k: 'NVDA ordinary day', v: '2.31%', up: false, note: 'already a volatile stock' },
        { k: 'NVDA earnings day', v: '6.20%', up: true, note: 'the day after the print' },
        { k: 'Multiple', v: '2.69x', up: true, note: 'Welch t = 3.10' },
      ] },
    },
    {
      role: 'chips', prio: 1, bg: V('wafer-arm.mp4'),
      eyebrow: 'The one that leans',
      head: 'Broadcom went up\nsixteen times',
      say: 'One name did lean. Broadcom closed higher sixteen times.',
      ask: 'Sixteen out of twenty two. Seventy three percent.',
      visual: { kind: 'rows', rows: [
        { k: 'AVGO prints', v: '22', up: true, note: 'same window' },
        { k: 'Closed higher', v: '16', up: true, note: 'the only lean in the set' },
        { k: 'Share up', v: '72.7%', up: true, note: 'well above the group' },
      ] },
    },
    {
      role: 'chips', prio: 1, bg: V('paper-crowd.mp4'),
      eyebrow: 'A fair question',
      head: 'Then Broadcom\nis the trade?',
      say: 'So is Broadcom the one you should be watching?',
      ask: 'Hold on. Look at how many prints that is.',
      visual: { kind: 'stat', label: 'BEFORE YOU ACT ON IT', value: 'CHECK n',
        sub: 'a lean on 22 prints is not yet an edge', up: false },
    },
    {
      role: 'chips', prio: 1, bg: V('quantum-fridge.mp4'),
      eyebrow: 'Before you use it',
      head: 'Twenty two is\na small number',
      say: 'Before you build anything on that, twenty two is small.',
      ask: 'One name out of ten leaning is what chance looks like.',
      visual: { kind: 'stat', label: 'WHY WE ARE NOT CALLING IT AN EDGE', value: 'n = 22',
        sub: 'with ten names, one leaning is expected by chance', up: false },
    },
    {
      role: 'chips', prio: 1, bg: V('humanoid-robot.mp4'),
      eyebrow: 'The other side',
      head: 'Four names\nleaned down',
      say: 'Four names leaned the other way, at thirty nine percent.',
      ask: 'Tesla, AMD, Micron and Apple, all the same number.',
      visual: { kind: 'rows', rows: [
        { k: 'TSLA AMD MU AAPL', v: '39.1%', up: false, note: 'nine of twenty three each' },
        { k: 'AVGO', v: '72.7%', up: true, note: 'leaning the other way' },
        { k: 'Everything together', v: '47.4%', up: false, note: 'the leans cancel out' },
      ] },
    },
    {
      role: 'chips', prio: 1, bg: V('gold-vault-bars.mp4'),
      eyebrow: 'Put together',
      head: 'The leans\ncancel',
      say: 'Put them all together and the leans cancel each other.',
      ask: 'Which is exactly what a coin looks like.',
      visual: { kind: 'stat', label: 'TEN NAMES POOLED', value: '47.4%',
        sub: 'the individual leans do not survive pooling', up: false },
    },
    {
      role: 'chips', prio: 1, bg: V('exchange-flags.mp4'),
      eyebrow: 'The honest summary',
      head: 'One rule.\nOne exception',
      say: 'One rule held across every name. One name bent it.',
      ask: 'And the bend is inside what chance produces.',
      visual: { kind: 'versus', aK: 'Size holds', aV: '10 / 10', bK: 'Direction leans', bV: '1 / 10' },
    },

    {
      role: 'evidence', prio: 1, bg: V('chip-macro-grey.mp4'),
      eyebrow: 'Look at Google',
      head: 'Google leaned up,\nbarely',
      say: 'Google closed higher thirteen times out of twenty three.',
      ask: 'Fifty six percent. Close enough to a coin to be one.',
      visual: { kind: 'rows', rows: [{ k: 'GOOGL up', v: '13 / 23', up: true, note: '56.5%' },{ k: 'META up', v: '11 / 23', up: false, note: '47.8%' },{ k: 'MSFT up', v: '11 / 23', up: false, note: '47.8%' } ] },
    },
    {
      role: 'evidence', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'And the group',
      head: 'Four names sat\nat thirty nine',
      say: 'Four separate names landed on exactly thirty nine percent.',
      ask: 'Nine out of twenty three, four times over.',
      visual: { kind: 'stat', label: 'TSLA · AMD · MU · AAPL', value: '9 / 23 EACH', sub: 'four names, the identical count', up: false },
    },
    {
      role: 'chips', prio: 1, bg: V('scale-few-vs-many.mp4'),
      eyebrow: 'Do the arithmetic',
      head: 'Ten names,\none lean',
      say: 'Do the arithmetic on that one lean for a second.',
      ask: 'Toss ten fair coins twenty two times each.',
      visual: { kind: 'stat', label: 'THE QUESTION TO ASK', value: 'IS ONE LEAN ODD?', sub: 'with ten names, chance produces leans', up: false },
    },
    {
      role: 'chips', prio: 1, bg: V('steel-balls.mp4'),
      eyebrow: 'The answer',
      head: 'One of them will\nlook special',
      say: 'One of them will look special. That is what chance does.',
      ask: 'You only call it an edge if it survives the next twenty.',
      visual: { kind: 'stat', label: 'THE TEST WE WOULD ACCEPT', value: 'THE NEXT 20', sub: 'a lean that repeats out of sample', up: true },
    },
    {
      role: 'chips', prio: 1, bg: V('mirror-city.mp4'),
      eyebrow: 'So we hold it open',
      head: 'We are not calling\nBroadcom an edge',
      say: 'So we are not calling Broadcom an edge. We are logging it.',
      ask: 'If it holds for another twenty prints, we will say so.',
      visual: { kind: 'rows', rows: [{ k: 'AVGO now', v: '16 / 22', up: true, note: '72.7% - logged, not claimed' }, { k: 'What would convince us', v: 'n = 42', up: true, note: 'the lean surviving another 20' }, { k: 'What we say today', v: 'UNPROVEN', up: false, note: 'and we keep counting' }] },
    },
    {
      role: 'chips', prio: 1, bg: V('wafer-spin-clean.mp4'),
      eyebrow: 'That is the discipline',
      head: 'Logging is not\nthe same as claiming',
      say: 'Logging a thing is not the same as claiming it.',
      ask: 'Most of the distance between good and bad numbers is that gap.',
      visual: { kind: 'versus', aK: 'What we do', aV: 'LOG IT', bK: 'What we avoid', bV: 'CLAIM IT' },
    },
    // ── 06 WHAT THIS DOES NOT SAY ────────────────────────────────────────────
    {
      role: 'verdict', prio: 1, bg: V('temple-storm.mp4'),
      eyebrow: 'The limits',
      head: 'What we did\nnot prove',
      say: 'Here is what this does not prove, stated plainly.',
      ask: 'We owe you the other side of it.',
      visual: { kind: 'stat', label: 'THE PART MOST VIDEOS SKIP', value: 'THE LIMITS',
        sub: 'a number is only as good as what it cannot say', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('geo-corridor-light.mp4'),
      eyebrow: 'Limit one',
      head: 'Ten names\nis not the market',
      say: 'Ten megacaps is not the whole market.',
      ask: 'Small caps and thin names may behave differently.',
      visual: { kind: 'stat', label: 'LIMIT 1', value: 'TEN NAMES',
        sub: 'megacap only - do not extend it to everything', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('skyline-sunrise-fog.mp4'),
      eyebrow: 'Limit two',
      head: 'Six years is\none regime',
      say: 'Six years covers one interest rate regime, roughly.',
      ask: 'A different decade could give a different answer.',
      visual: { kind: 'stat', label: 'LIMIT 2', value: 'ONE REGIME',
        sub: '2021 to 2026 - not a century of evidence', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('geo-radar-dusk.mp4'),
      eyebrow: 'Limit three',
      head: 'A coin flip is\nnot a free trade',
      say: 'And a coin flip in direction does not make it free money.',
      ask: 'Buying the size costs you something up front.',
      visual: { kind: 'stat', label: 'LIMIT 3', value: 'IT IS PRICED',
        sub: 'the expected move is already in what you pay', up: false },
    },

    // ── 07 THREE NUMBERS ─────────────────────────────────────────────────────
    {
      role: 'verdict', prio: 1, bg: V('golden-bell.mp4'),
      eyebrow: 'What to watch',
      head: 'Three numbers,\nWednesday',
      say: 'So here are three numbers to check on Wednesday.',
      ask: 'All three are public. You do not need us.',
      visual: { kind: 'stat', label: 'THE CHECKLIST', value: 'THREE',
        sub: 'every one of them is a public number', up: true },
    },
    {
      role: 'verdict', prio: 1, bg: V('pcb-one-chip-lit.mp4'),
      eyebrow: 'Number one',
      head: 'Six point\ntwo percent',
      say: 'One. The size of the move, against six point two.',
      ask: 'Near it is ordinary. Far from it is the story.',
      visual: { kind: 'rows', rows: [
        { k: 'NVDA earnings day average', v: '6.20%', up: true, note: 'the baseline to compare against' },
        { k: 'Its ordinary day', v: '2.31%', up: false, note: 'for reference' },
        { k: 'Wednesday', v: '?', up: true, note: 'near 6% means a normal reaction' },
      ] },
    },
    {
      role: 'verdict', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'Number two',
      head: 'Twelve of\ntwenty three',
      say: 'Two. The running count. Eleven of twenty two so far.',
      ask: 'After Wednesday it is out of twenty three.',
      visual: { kind: 'rows', rows: [
        { k: 'NVDA up-count now', v: '11 / 22', up: false, note: 'exactly 50.0%' },
        { k: 'After Wednesday', v: '? / 23', up: true, note: 'the count only moves one step' },
        { k: 'Watch for', v: 'drift', up: true, note: 'one print does not change a coin' },
      ] },
    },
    {
      role: 'verdict', prio: 1, bg: V('scale-few-vs-many.mp4'),
      eyebrow: 'Number three',
      head: 'Forty seven\npoint four',
      say: 'Three. The pooled share across all ten names.',
      ask: 'If that ever leaves the forties, something changed.',
      visual: { kind: 'stat', label: 'POOLED SHARE UP - ALL TEN NAMES', value: '47.4%',
        sub: 'this is the number that would have to move', up: false },
    },
    {
      role: 'verdict', prio: 1, bg: V('desks-dawn.mp4'),
      eyebrow: 'The point',
      head: 'You can check\nall of it',
      say: 'Every number here came from public daily bars.',
      ask: 'Pull them yourself. That is the whole point.',
      visual: { kind: 'rows', rows: [
        { k: 'Source', v: 'daily bars', up: true, note: 'nothing proprietary' },
        { k: 'Window', v: '2021 - 2026', up: true, note: 'fixed before we ran it' },
        { k: 'Prints', v: '228', up: true, note: 'all of them, none dropped' },
      ] },
    },
    {
      role: 'verdict', prio: 1, bg: V('rise-glass-tower.mp4'),
      eyebrow: 'Not advice',
      head: 'This is not\nadvice',
      say: 'This is not advice and it is not a forecast.',
      ask: 'It is a count, and counts can be checked.',
      visual: { kind: 'stat', label: 'WHAT THIS IS', value: 'A COUNT',
        sub: 'educational only - not investment advice', up: true },
    },
    {
      role: 'verdict', prio: 1, bg: V('desks-dawn.mp4'),
      eyebrow: 'Do it yourself',
      head: 'Three steps,\nten minutes',
      say: 'If you want to redo this yourself, it is three steps.',
      ask: 'Any free data source has what you need.',
      visual: { kind: 'rows', rows: [{ k: 'Step one', v: 'earnings dates', up: true, note: 'public calendar' }, { k: 'Step two', v: 'next-day close', up: true, note: 'daily bars' }, { k: 'Step three', v: 'compare', up: true, note: 'against every other day' }] },
    },
    {
      role: 'verdict', prio: 1, bg: V('glass-tube-array.mp4'),
      eyebrow: 'One rule when you do',
      head: 'Fix the window\nbefore you look',
      say: 'One rule when you do it. Fix the window before you look.',
      ask: 'If you pick the years after seeing the answer, you have no answer.',
      visual: { kind: 'stat', label: 'THE ONLY RULE THAT MATTERS', value: 'DECIDE FIRST', sub: 'otherwise you are describing the past', up: true },
    },
    {
      role: 'verdict', prio: 1, bg: V('tape-wall-scroll.mp4'),
      eyebrow: 'And publish the n',
      head: 'Always carry\nthe sample size',
      say: 'And carry the sample size everywhere the number goes.',
      ask: 'A percentage without an n is not a finding.',
      visual: { kind: 'stat', label: 'A NUMBER WITHOUT ITS n', value: 'IS NOT EVIDENCE', sub: '47.4% means nothing until you say 228', up: true },
    },
    {
      role: 'verdict', prio: 1, bg: V('columns-goldenhour.mp4'),
      eyebrow: 'To recap',
      head: 'Size is real.\nDirection is not',
      say: 'So to recap. The size is real, measurable and repeatable.',
      ask: 'The direction, across two hundred twenty eight prints, is a coin.',
      visual: { kind: 'versus', aK: 'Size', aV: '3.45x REAL', bK: 'Direction', bV: '47.4% COIN' },
    },
    {
      role: 'verdict', prio: 1, bg: V('nyse-flags.mp4'),
      eyebrow: 'Your turn',
      head: 'Tell us what\nto count next',
      say: 'If there is a claim you keep hearing, put it in the comments.',
      ask: 'We will count it and bring the number back.',
      visual: { kind: 'stat', label: 'WHAT GOES IN THE COMMENTS', value: 'A CLAIM',
        sub: 'we pick one and run the same test on it', up: true },
    },
  ],

  voice: VOICE_LFEARN,
};
