// 자동 생성 — scripts/tts-ad.mjs (수동 편집 금지, 재생성으로만 갱신)

export type AdLine = { id: string; f: string; sec: number; text: string };

export const VOICE_AD = {
  base: 'shorts/audio/adv5',
  lines: [
    { id: 'open', f: 'open.mp3', sec: 1.85, text: "Every options signal. One screen." },
    { id: 'morn', f: 'morn.mp3', sec: 1.9, text: "A morning briefing, before the bell." },
    { id: 'pain', f: 'pain.mp3', sec: 2.47, text: "Max pain. Where most options expire worthless." },
    { id: 'gamma', f: 'gamma.mp3', sec: 2.8, text: "Gamma flip. Where dealers stop cushioning the move." },
    { id: 'whale', f: 'whale.mp3', sec: 2.97, text: "Whale flow. The size institutions are actually moving." },
    { id: 'dark', f: 'dark.mp3', sec: 2.15, text: "Dark pool. The volume nobody sees." },
    { id: 'ai', f: 'ai.mp3', sec: 2.25, text: "And Claude reads the whole book down to one line." },
    { id: 'close', f: 'close.mp3', sec: 1.8, text: "A closing briefing, every single day." },
    { id: 'uc', f: 'uc.mp3', sec: 2.37, text: "And Undercurrent. The money moving behind the news." },
    { id: 'free', f: 'free.mp3', sec: 1.02, text: "All of it. Free." },
    { id: 'tag1', f: 'tag1.mp3', sec: 1.82, text: "Options data institutions pay for." },
    { id: 'tag2', f: 'tag2.mp3', sec: 1.75, text: "Briefed before the bell, every day." },
    { id: 'tag3', f: 'tag3.mp3', sec: 1.3, text: "SIGNUM HQ. Free." },
    { id: 'cp1a', f: 'cp1a.mp3', sec: 1.42, text: "Most options expire worthless." },
    { id: 'cp1b', f: 'cp1b.mp3', sec: 2.25, text: "And there is one price where the most of them do." },
    { id: 'cp1c', f: 'cp1c.mp3', sec: 1.55, text: "That price is called max pain." },
    { id: 'cp1d', f: 'cp1d.mp3', sec: 3.2, text: "It is not a prediction. It is just where the contracts are stacked." },
    { id: 'cp1e', f: 'cp1e.mp3', sec: 2.32, text: "On AMD right now, that price is four fifty." },
    { id: 'cp1f', f: 'cp1f.mp3', sec: 2.52, text: "Every open option contract sits at some strike price." },
    { id: 'cp1g', f: 'cp1g.mp3', sec: 4.4, text: "Add up what all of them would pay out at expiry, and one price makes that total the smallest." },
    { id: 'cp1h', f: 'cp1h.mp3', sec: 4.22, text: "That is max pain. The level where option buyers, as a group, get the least back." },
    { id: 'cp1i', f: 'cp1i.mp3', sec: 4.1, text: "The dealers who sold those options hedge around it, and that hedging is real buying and selling." },
    { id: 'cp1j', f: 'cp1j.mp3', sec: 2.62, text: "Whether that actually pulls price toward it is debated." },
    { id: 'cp1k', f: 'cp1k.mp3', sec: 2.1, text: "What is not debated is where the contracts sit." },
    { id: 'cp1l', f: 'cp1l.mp3', sec: 3.8, text: "It moves as contracts open and close. It is a level, not a target." },
    { id: 'cp1m', f: 'cp1m.mp3', sec: 1.45, text: "So how do you actually use it?" },
    { id: 'cp1n', f: 'cp1n.mp3', sec: 4.05, text: "When price sits well above max pain, the crowded side is upside calls." },
    { id: 'cp1o', f: 'cp1o.mp3', sec: 2.35, text: "When it sits below, the crowd is leaning short." },
    { id: 'cp1p', f: 'cp1p.mp3', sec: 3.27, text: "It tells you where the crowd is. It does not tell you where price goes." },
    { id: 'c2a', f: 'c2a.mp3', sec: 1.9, text: "RSI above seventy means overbought." },
    { id: 'c2b', f: 'c2b.mp3', sec: 1.65, text: "Almost everyone reads that as sell." },
    { id: 'c2c', f: 'c2c.mp3', sec: 1.7, text: "Here is what RSI actually measures." },
    { id: 'c2d', f: 'c2d.mp3', sec: 1.75, text: "Average gains against average losses." },
    { id: 'c2e', f: 'c2e.mp3', sec: 1.55, text: "Over the last fourteen trading days." },
    { id: 'c2f', f: 'c2f.mp3', sec: 1.72, text: "Above seventy just means gains won." },
    { id: 'c2g', f: 'c2g.mp3', sec: 1.6, text: "It says nothing about what comes next." },
    { id: 'c2h', f: 'c2h.mp3', sec: 2.05, text: "AMD crossed seventy three times this spring." },
    { id: 'c2i', f: 'c2i.mp3', sec: 1.8, text: "It was higher five days later every time." },
    { id: 'c2j', f: 'c2j.mp3', sec: 2.32, text: "So we counted every crossing since 2021." },
    { id: 'c2k', f: 'c2k.mp3', sec: 2.12, text: "Twelve large caps. Three hundred eighty six." },
    { id: 'c2l', f: 'c2l.mp3', sec: 1.95, text: "Higher five days later, fifty seven percent." },
    { id: 'c2m', f: 'c2m.mp3', sec: 1.65, text: "On any given day, fifty three." },
    { id: 'c2n', f: 'c2n.mp3', sec: 1.65, text: "A four point gap. That is noise." },
    { id: 'c2o', f: 'c2o.mp3', sec: 2.07, text: "RSI over seventy is not a sell signal." },
    { id: 'c2p', f: 'c2p.mp3', sec: 1.9, text: "It describes the trend you are already in." },
    { id: 'c2q', f: 'c2q.mp3', sec: 2.35, text: "On AMD right now, RSI is forty five." },
  ] as AdLine[],
};
