import { ReactNode } from 'react';
import Link from 'next/link';
import {
    AlertTriangle, Scale, Ban, CreditCard, RefreshCw, Shield,
    Database, Users, LogOut, CloudOff, FileText, Gavel, BookOpen, Globe
} from 'lucide-react';

export interface TermsSection {
    icon: any;
    color: string;
    title: string;
    content: ReactNode;
    highlight?: boolean;
}

export interface TermsMeta {
    pageTitle: string;
    lastUpdated: string;
    intro: string;
    effectiveDate: string;
    effectiveDateBold: string;
    backLink: string;
}

export const meta: TermsMeta = {
    pageTitle: 'Terms of Service',
    lastUpdated: 'Last Updated: 2026-02-12',
    intro: 'These Terms of Service ("Terms") govern your access to and use of the SIGNUM HQ platform and services. By accessing or using the Service, you agree to be bound by these Terms.',
    effectiveDate: 'These Terms are effective as of ',
    effectiveDateBold: 'February 12, 2026',
    backLink: '← Back to Login',
};

export const sections: TermsSection[] = [
    {
        icon: BookOpen,
        color: 'text-slate-400',
        title: 'Article 1. Purpose',
        content: (
            <p>These Terms establish the rights, obligations, and responsibilities between SIGNUM HQ (the &quot;Company&quot;) and users (&quot;Members&quot;) regarding the use of the SIGNUM HQ platform and associated services.</p>
        ),
    },
    {
        icon: FileText,
        color: 'text-indigo-400',
        title: 'Article 2. Definitions',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li><strong>&quot;Service&quot;</strong> refers to all data, AI analysis, visualizations, and tools provided by SIGNUM HQ, accessible via any device (PC, mobile, etc.).</li>
                <li><strong>&quot;Member&quot;</strong> refers to any individual who agrees to these Terms and completes the registration process.</li>
                <li><strong>&quot;Tactical Order&quot;</strong> refers to statistical signals generated by algorithms for specific market conditions (e.g., BUY, HOLD, SELL). <strong>These are for reference only and do not constitute trade orders.</strong></li>
                <li><strong>&quot;Premium Service&quot;</strong> refers to paid subscription tiers that provide enhanced data analysis, real-time signals, AI reports, and other advanced features.</li>
            </ol>
        ),
    },
    {
        icon: AlertTriangle,
        color: 'text-amber-400',
        title: 'Article 3. Nature of Financial Information & Investment Disclaimer',
        highlight: true,
        content: (
            <ol className="list-decimal list-inside space-y-3">
                <li><strong>Information Only:</strong> All data, analysis, and information provided through SIGNUM HQ (including Gamma Exposure, Options Flow, Max Pain, Dark Pool Tracker, Alpha Score, Tactical Orders, etc.) are <strong>statistical reference materials based on historical data and do not constitute investment advice, recommendations, or solicitations to buy or sell any securities.</strong></li>
                <li><strong>Investment Responsibility:</strong> All financial investments carry risk of loss. <strong>All investment decisions and their resulting gains or losses are solely the responsibility of the user.</strong> The Company assumes no legal liability for investment outcomes based on information provided through the Service.</li>
                <li><strong>Not a Registered Investment Adviser:</strong> <strong>The Company is not registered as an investment adviser with the U.S. Securities and Exchange Commission (SEC), FINRA, or any comparable regulatory body.</strong> The Service does not provide investment advisory, portfolio management, or fiduciary services.</li>
                <li><strong>No Guarantee of Past Performance:</strong> Historical statistics, backtest results, alpha scores, and other data-derived metrics presented on the Service <strong>do not guarantee or predict future investment performance.</strong></li>
            </ol>
        ),
    },
    {
        icon: Ban,
        color: 'text-rose-400',
        title: 'Article 4. Restrictions & Prohibited Activities',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li><strong>Account Sharing:</strong> Each Member&apos;s account is for personal use only and may not be transferred, lent, or shared with others.</li>
                <li><strong>Data Scraping:</strong> Automated collection, processing, or redistribution of Service data using robots, spiders, scrapers, or other automated means without prior written consent is strictly prohibited.</li>
                <li><strong>Reverse Engineering:</strong> Decompiling, disassembling, reverse-engineering, or attempting to derive the source code, algorithms, or analysis logic of the Service is prohibited.</li>
                <li><strong>Illegal Activities:</strong> Using information from the Service for market manipulation, insider trading, or other activities that violate applicable securities laws is prohibited.</li>
                <li><strong>Misinformation:</strong> Using the Service to disseminate false or misleading information is prohibited.</li>
                <li><strong>Enforcement:</strong> Violation of the above may result in <strong>immediate suspension or termination of the Member&apos;s account without prior notice,</strong> and the Company may pursue civil and criminal remedies.</li>
            </ol>
        ),
    },
    {
        icon: CreditCard,
        color: 'text-emerald-400',
        title: 'Article 5. Subscriptions & Payments',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li>The Company offers paid services (Premium, Pro, etc.). Pricing and scope for each tier are published within the Service.</li>
                <li>Recurring subscriptions will <strong>automatically renew on a monthly or annual basis</strong> unless the Member cancels before the end of the billing period.</li>
                <li>The Company may modify subscription pricing with at least 30 days&apos; prior notice via in-service announcement or email. Updated pricing applies from the next billing cycle.</li>
            </ol>
        ),
    },
    {
        icon: RefreshCw,
        color: 'text-cyan-400',
        title: 'Article 6. Service Modifications & Interruptions',
        content: (
            <ol className="list-decimal list-inside space-y-3">
                <li><strong>Modifications:</strong> The Company may modify or update the Service in whole or in part as needed for operational or technical reasons.</li>
                <li>
                    <strong>Interruptions:</strong> The Service may be temporarily interrupted for the following reasons, and <strong>the Company shall not be held liable for any resulting damages:</strong>
                    <ul className="list-disc list-inside ml-4 mt-2 space-y-1 text-slate-400">
                        <li>Scheduled maintenance, server upgrades, or infrastructure replacements</li>
                        <li>Force majeure events (natural disasters, government actions, exchange halts)</li>
                        <li>Third-party data provider (API) outages or service disruptions</li>
                        <li>Telecommunications service provider interruptions</li>
                    </ul>
                </li>
                <li><strong>Termination:</strong> If the Company permanently discontinues the Service, it will provide at least 30 days&apos; notice and issue pro-rated refunds to paid subscribers for unused portions of their subscription.</li>
            </ol>
        ),
    },
    {
        icon: CreditCard,
        color: 'text-teal-400',
        title: 'Article 7. Refund Policy',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li><strong>Digital Content:</strong> The Service provides instant access to premium data and analysis reports upon payment, qualifying as &quot;digital content.&quot;</li>
                <li><strong>Limited Refunds:</strong> Once a Member has accessed paid data, viewed reports, or connected to the Service at least once, <strong>the Service value is considered consumed and refunds may be limited.</strong></li>
                <li><strong>Exception:</strong> A full refund is available within 7 days of payment if there is no record of Service access or data viewing.</li>
                <li><strong>Refund Process:</strong> Refund requests may be submitted via the Service or email (<a href="mailto:contact@signumhq.com" className="text-cyan-400 hover:underline">contact@signumhq.com</a>) and will be processed within 7 business days.</li>
            </ol>
        ),
    },
    {
        icon: Shield,
        color: 'text-violet-400',
        title: 'Article 8. Intellectual Property',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li>All designs, text, charts, algorithms, data visualizations, trademarks (<strong>SIGNUM HQ, Alpha Engine, Tactical Order</strong>, etc.), and other content within the Service are the <strong>intellectual property of the Company</strong> and are protected under applicable copyright and intellectual property laws.</li>
                <li>Members may not use, reproduce, distribute, or provide the Service&apos;s content to third parties <strong>for commercial purposes without prior written consent.</strong></li>
                <li>Copyright for any user-generated content posted within the Service belongs to the respective Member, though the Company may use such content within the scope of Service operations.</li>
            </ol>
        ),
    },
    {
        icon: Database,
        color: 'text-sky-400',
        title: 'Article 9. Data Disclaimer & Third-Party Data',
        highlight: true,
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li><strong>No Warranty:</strong> The Company does not guarantee the accuracy, completeness, timeliness, or fitness for any particular purpose of the Service. <strong>The Service is provided &quot;AS-IS&quot; without any warranty</strong>, express or implied.</li>
                <li><strong>System Failures:</strong> The Company shall not be held liable for information omissions, errors, or resulting damages caused by system errors, data delays, network failures, or other technical issues.</li>
                <li><strong>Third-Party Data:</strong> Market data, options data, indices, and other financial information provided through the Service are sourced from third-party providers (exchanges, data vendors, etc.), and <strong>the Company does not guarantee the accuracy, completeness, or real-time nature of such data.</strong></li>
                <li><strong>Data Latency:</strong> Even data displayed as &quot;real-time&quot; may have time delays compared to actual market data. The Company is not responsible for any damages arising from such delays.</li>
            </ol>
        ),
    },
    {
        icon: Scale,
        color: 'text-orange-400',
        title: 'Article 10. Limitation of Liability',
        highlight: true,
        content: (
            <ol className="list-decimal list-inside space-y-3">
                <li><strong>Maximum Liability:</strong> In the event of damages caused by the Company&apos;s fault, the Company&apos;s liability shall not exceed <strong>the total service fees paid by the Member during the 3 months immediately preceding the date of damage.</strong> For free-tier users, the Company bears no liability.</li>
                <li><strong>Indirect Damages:</strong> The Company shall not be liable for <strong>indirect, special, consequential, punitive, or incidental damages, nor for loss of profits or anticipated gains</strong> arising from use of the Service.</li>
                <li><strong>Investment Loss Disclaimer:</strong> The Company is <strong>not liable under any circumstances for financial losses</strong> resulting from investment decisions made based on information provided through the Service.</li>
            </ol>
        ),
    },
    {
        icon: Scale,
        color: 'text-red-400',
        title: 'Article 11. Arbitration & Class Action Waiver',
        highlight: true,
        content: (
            <ol className="list-decimal list-inside space-y-3">
                <li><strong>Binding Arbitration:</strong> Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved through <strong>binding arbitration</strong> rather than in court, except for disputes that qualify for small claims court.</li>
                <li><strong>Class Action Waiver:</strong> <strong>You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.</strong> You waive any right to participate in a class action lawsuit or class-wide arbitration against the Company.</li>
                <li><strong>Opt-Out:</strong> You may opt out of this arbitration provision by notifying the Company in writing within 30 days of first accepting these Terms at <a href="mailto:contact@signumhq.com" className="text-cyan-400 hover:underline">contact@signumhq.com</a>.</li>
            </ol>
        ),
    },
    {
        icon: Users,
        color: 'text-rose-400',
        title: 'Article 12. Age Restriction',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li>The Service is intended for users <strong>aged 18 and above.</strong></li>
                <li>By registering for and using the Service, you certify that you are at least 18 years of age. <strong>The Company is not responsible for any issues arising from minors using the Service</strong> without parental consent, and such accounts may be terminated.</li>
            </ol>
        ),
    },
    {
        icon: LogOut,
        color: 'text-pink-400',
        title: 'Article 13. Account Termination',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li><strong>Voluntary Termination:</strong> Members may request account deletion at any time through Service settings or email (<a href="mailto:contact@signumhq.com" className="text-cyan-400 hover:underline">contact@signumhq.com</a>).</li>
                <li><strong>Data Deletion:</strong> Upon termination, personal data will be promptly deleted except where retention is required by applicable law.</li>
                <li><strong>Company-Initiated Termination:</strong> The Company may terminate accounts for Terms violations or service disruption, with prior notice (or post-notice in urgent cases).</li>
                <li><strong>Paid Subscriptions:</strong> Upon cancellation, paid subscribers retain access until the end of the current billing period. No further charges will be applied.</li>
            </ol>
        ),
    },
    {
        icon: CloudOff,
        color: 'text-gray-400',
        title: 'Article 14. Force Majeure',
        content: (
            <p>The Company shall not be held liable for failure to provide the Service due to circumstances <strong>beyond its reasonable control,</strong> including but not limited to natural disasters, war, terrorism, government actions, regulatory changes, exchange emergency halts, power outages, or telecommunications failures.</p>
        ),
    },
    {
        icon: FileText,
        color: 'text-purple-400',
        title: 'Article 15. Amendments',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li>The Company may modify these Terms within the bounds of applicable law.</li>
                <li>Changes will be announced at least <strong>7 days in advance</strong> (or <strong>30 days for changes unfavorable to Members</strong>) via in-service notice or email.</li>
                <li>Continued use of the Service after the effective date of modified Terms constitutes <strong>acceptance of the modified Terms.</strong></li>
                <li>Members who do not agree to modified Terms may discontinue use and terminate their accounts.</li>
            </ol>
        ),
    },
    {
        icon: Gavel,
        color: 'text-amber-300',
        title: 'Article 16. Governing Law & Dispute Resolution',
        content: (
            <ol className="list-decimal list-inside space-y-2">
                <li>These Terms shall be governed by and construed in accordance with the <strong>laws of the Republic of Korea.</strong></li>
                <li>Subject to Article 11 (Arbitration), any disputes arising from these Terms shall be submitted to the <strong>court of competent jurisdiction at the Company&apos;s principal place of business.</strong></li>
                <li>By agreeing to these Terms, international users consent to the <strong>application of Korean law and the jurisdiction of Korean courts.</strong></li>
            </ol>
        ),
    },
];
