#!/usr/bin/env node
/* ============================================================================
 * reddit-comment — 레딧에 «클릭 없이» 댓글을 단다. 그리고 게시 여부를 스스로 검증한다.
 *
 * ★2026-09-22 만든 이유 (대표 지시: 「브라우저 없는 경로 하나 더 뚫어」):
 *   발행 속도가 채널마다 10배씩 차이 난다 —
 *     · 블루스카이 CLI: **건당 30초**(브라우저 없음)
 *     · 브라우저로 UI 를 모는 채널: **건당 5~10분**(작성칸 찾기·좌표·버튼 재측정…)
 *   완전히 브라우저가 없는 공개 API 는 Mastodon·dev.to 뿐인데 둘 다 «가입»이 필요하다(내 안전선).
 *   그래서 차선을 뚫었다: **로그인된 페이지 «안에서» 그 사이트의 API 를 직접 부른다.**
 *   쿠키를 꺼내지 않는다(그건 세션 탈취다). 브라우저는 쓰되 «클릭을 안 한다».
 *   실측: 댓글 하나가 수 초. UI 조작 대비 20배 이상 빠르다.
 *
 * 왜 레딧인가: 팔로워가 0이어도 도달하는 몇 안 되는 채널이고(§reddit-is-the-one-channel-that-works),
 *   «글»은 전부 스팸필터에 죽지만 «댓글»은 산다(§reddit-posts-are-all-spam-filtered).
 *
 * 안전선(스크립트가 강제한다):
 *   · 본문 링크 금지 — 레딧에서 링크는 삭제 사유다. http(s) 가 있으면 거부한다.
 *   · AI 작성 금지 서브 제외: r/options · r/StockMarket · r/investing · r/iosapps · r/Daytrading
 *     (+9/25 규칙 실측: r/ValueInvesting · r/Bogleheads · r/economy · r/personalfinance · r/quant · r/CanadianInvestor · r/fatFIRE · r/JapanFinance)
 *   · 하루 3건(UTC일)·8분 간격은 «사이클 규칙»이다. 이 스크립트는 한 번에 하나만 올린다.
 *
 * 사용:
 *   ego-browser nodejs < scripts/reddit-comment.mjs            상태만 확인(누가 로그인됐나)
 *   작업 파일을 먼저 쓰고 같은 명령을 돌린다:
 *     echo '{"parent":"t3_xxxx","file":"~/signum-ego-io/<날짜>/c.txt"}' > ~/signum-ego-io/<KST 날짜>/reddit-task.json  (file 은 절대경로)
 *   ⚠ 환경변수·argv 는 쓸 수 없다 — ego-browser 는 스크립트를 stdin 으로 받는 별도 런타임이라
 *     셸의 env 가 전달되지 않는다(2026-09-22 실측: REDDIT_PARENT 가 undefined 였다). 그래서 «파일»로 넘긴다.
 *
 * 게시 «했다»고 적기 전에 이 스크립트가 직접 확인한다: 스레드 JSON 을 다시 읽어
 * 내 댓글이 실제로 보이고 removed 가 아닌지 본다. 200 응답만으로는 «게시됨»이 아니다.
 * ========================================================================== */
const L = await import('file:///Users/eunhoon/.gemini/antigravity/scratch/stock2/scripts/ego/lib.mjs');
const { readFileSync } = await import('node:fs');

// ★2026-09-25 규칙 전수 실측(/r/<sub>/about/rules.json, 48개 서브에서 AI·LLM·ChatGPT·generated 검색)으로 확장:
//   valueinvesting(«AI-generated content» 삭제 사유) · bogleheads(«AI-generated responses» 금지) · economy(«ChatGPT-generated articles» 금지)
//   personalfinance(«AI-generated content») · quant(«No AI Content») · canadianinvestor(«No AI») · fatfire(«No … AI posts») · japanfinance(«LLM-generated content»)
// ★2026-09-29 규칙 실측: amd_stock(«No AI-Generated Content :: All posts and comments must be human-written»)
// ★2026-09-30 12시 전 세계 서브 39곳 규칙 원문(로그인 세션 about/rules.json, ~/signum-ego-io/2026-09-30/rd-global/rd-global-rules.json):
//   indianstockmarket(«AI Slops: All content generated by AI will be removed») · personalfinanceindia(«No AI Slop … unedited AI outputs»)
//   vosfinances(«Peu d'effort, fantaisie ou utilisation d'IA») · spainfire(«Evita publicar AI slop») · italiapersonalfinance(«No contenuti generati da AI»)
//   befire(«No AI slop // No AI websites // No AI apps») · dutchfire(«Geen gegenereerde reacties … ChatGPT») · beleggen(«Geen AI content»)
//   malaysianpf(«No AI slop») · ukinvesting(«R6 … bots, which will be banned on sight» — 자동 게시는 봇으로 본다, 보수적으로 금지)
const BANNED = ['options', 'stockmarket', 'investing', 'iosapps', 'daytrading', 'valueinvesting', 'bogleheads', 'economy', 'personalfinance', 'quant', 'canadianinvestor', 'fatfire', 'japanfinance', 'amd_stock',
  'indianstockmarket', 'personalfinanceindia', 'vosfinances', 'spainfire', 'italiapersonalfinance', 'befire', 'dutchfire', 'beleggen', 'malaysianpf', 'ukinvesting'];
const TASK = await L.taskPath('reddit-task.json');   // ~/signum-ego-io/<KST 날짜>/ (옛 /tmp/ego 도 읽는다 — 9/30 재부팅 소실 뒤)
L.assertFreshTask(TASK); // ★2026-10-04 낡은 작업 파일 거부(MISTAKES #52)
let task = {};
try { task = JSON.parse(readFileSync(TASK, 'utf8')); } catch { /* 없으면 상태 확인만 한다 */ }
const parent = String(task.parent || '').trim();   // t3_xxxx(글) 또는 t1_xxxx(댓글)
const text = task.file ? readFileSync(task.file, 'utf8').trim() : String(task.text || '').trim();

const list = await listTaskSpaces();
const sp = (list || []).find((s) => s.profileId === 'Profile 1') || (list || [])[0];
let ts;
try { ts = await L.takeSpaceOrExit(sp.id); } catch { console.log('작업공간을 못 잡았다 — 대표가 쓰는 중일 수 있다'); process.exit(1); }
await L.cleanupPages(ts, 2);
const page = await L.findPage(ts, /reddit/, null);
try { await page.goto('https://www.reddit.com/', { waitUntil: 'domcontentloaded' }); } catch { /* 느려도 그려진다 */ }
await L.wait(6000);

const me = await page.evaluate(async () => {
    try {
        const r = await fetch('https://www.reddit.com/api/me.json', { credentials: 'include' });
        const j = await r.json();
        return { name: j?.data?.name || null, uh: !!j?.data?.modhash, karma: j?.data?.total_karma ?? null };
    } catch (e) { return { err: String(e.message).slice(0, 80) }; }
});
console.log('로그인:', me.name || '(없음)', '· modhash', me.uh ? 'O' : 'X', '· 카르마', me.karma);
if (!me.name || !me.uh) { console.log('로그인되어 있지 않다 — 대표 로그인 1회 필요'); process.exit(1); }
if (!parent || !text) { console.log('\n상태 확인만 했다. 올리려면 ' + TASK + ' 에 {parent,file} 을 써 둔다.'); process.exit(0); }

// ── 안전선 ────────────────────────────────────────────────────────────────
// ★2026-10-03 링크 예외(좁게): 스레드 규칙이 자기 홍보·링크를 «명문으로» 허용하는 홍보 전용 스레드에서만
//   (예: r/IndiaInvestments «Show II : Promotional Content thread» — «we waive the no self promotion rule» · «Link only comments will be removed - you must provide a summary»).
//   셋이 모두 맞아야 한다: ① 작업 파일 allowLink:true ② 링크가 우리 스마트링크 «하나»(https://www.signumhq.com/app?from=reddit_*) ③ 부모 스레드 제목이 홍보 전용 스레드.
//   일반 스레드는 예전처럼 링크를 거부한다(레딧에서 링크는 삭제 사유).
const linkUrls = text.match(/https?:\/\/\S+/gi) || [];
const SMART_RE = /^https:\/\/www\.signumhq\.com\/app\?from=reddit_[a-z_]+$/i;
const linkOk = task.allowLink === true && linkUrls.length === 1 && SMART_RE.test(linkUrls[0]);
if (linkUrls.length && !linkOk) { console.log('⛔ 본문에 링크가 있다 — 레딧에서는 삭제 사유다. 거부한다. (홍보 전용 스레드에서만 allowLink:true + 스마트링크 1개 허용)'); process.exit(1); }
if (!/^t[13]_[a-z0-9]+$/i.test(parent)) { console.log('⛔ REDDIT_PARENT 형식이 아니다(t3_xxxx 또는 t1_xxxx)'); process.exit(1); }

// 어느 서브인지 확인해 금지 서브를 막는다
const parentInfo = await page.evaluate(async (id) => {
    try {
        const r = await fetch(`https://www.reddit.com/api/info.json?id=${id}`, { credentials: 'include' });
        const j = await r.json();
        const d = j?.data?.children?.[0]?.data || {};
        return { sub: d.subreddit || null, title: String(d.title || d.link_title || '') };
    } catch { return { sub: null, title: '' }; }
}, parent);
const sub = parentInfo.sub;
console.log('대상 서브:', sub || '(확인 실패)', linkUrls.length ? '· 스레드 «' + parentInfo.title.slice(0, 70) + '»' : '');
if (linkUrls.length && !/promotional content|self[- ]?promo|promo(tional)? thread|show ?(hn|ii)\b/i.test(parentInfo.title)) { console.log('⛔ 링크 댓글은 홍보 전용 스레드에서만 허용 — 이 스레드 제목이 아니다. 거부한다.'); process.exit(1); }
if (sub && BANNED.includes(String(sub).toLowerCase())) {
    console.log(`⛔ r/${sub} 는 AI 작성 금지 또는 제외 서브다. 거부한다.`); process.exit(1);
}

// ★2026-09-30 10시 사고 수리 — «같은 스레드 중복 금지»를 스크립트가 강제한다.
//   9/27 에 이미 답한 WSB «Weekly Earnings Thread Sep 28 - Oct 2»(1wq1q7n)에 두 번째 댓글을 달았다(pcwvtql).
//   원인: 원장이 별칭(wsb_earnings_thread)을 reddit 으로만 적어 «미실행 표면»으로 오판 + channels.json 게이트(until 10/2)를 안 읽었다.
//   → 부모(글/댓글)의 스레드 ID 를 구해 원장에 같은 스레드 주소가 있으면 거부한다(task.allowSameThread:true 로만 우회 — 대표 판단용).
const thread = await page.evaluate(async (id) => {
    try {
        const r = await fetch(`https://www.reddit.com/api/info.json?id=${id}`, { credentials: 'include' });
        const d = (await r.json())?.data?.children?.[0]?.data || {};
        return String(d.link_id || d.name || '').replace(/^t3_/, '') || null;
    } catch { return null; }
}, parent);
if (thread) {
    let led = [];
    try { led = JSON.parse(readFileSync('/Users/eunhoon/.gemini/antigravity/scratch/stock2/.agent/marketing/PUBLISH-LEDGER.json', 'utf8')).entries || []; } catch { /* 원장이 없으면 아래 검사 생략 */ }
    const prev = led.filter((e) => new RegExp(`/comments/${thread}(/|$)`).test(String(e.url || '')));
    if (prev.length && task.allowSameThread !== true) {
        console.log(`⛔ 같은 스레드(${thread})에 이미 우리 댓글이 있다 — 원장 ${prev.length}건: ${prev.map((e) => e.kst + ' ' + e.url).join(' · ')}. «같은 스레드 중복 금지» — 거부한다.`);
        process.exit(1);
    }
    console.log('스레드:', thread, '· 원장에 같은 스레드 없음');
}

// ── 게시 ─────────────────────────────────────────────────────────────────
const res = await page.evaluate(async (cfg) => {
    const me2 = await (await fetch('https://www.reddit.com/api/me.json', { credentials: 'include' })).json();
    const uh = me2?.data?.modhash;
    const body = new URLSearchParams({ api_type: 'json', thing_id: cfg.parent, text: cfg.text, uh });
    const r = await fetch('https://www.reddit.com/api/comment', {
        method: 'POST', credentials: 'include',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'X-Modhash': uh },
        body: body.toString(),
    });
    const t = await r.text();
    let j = null; try { j = JSON.parse(t); } catch { /* HTML 이 오면 아래에서 raw 로 본다 */ }
    const things = j?.json?.data?.things || [];
    return { status: r.status, errors: j?.json?.errors || null, id: things[0]?.data?.id || null,
             link: things[0]?.data?.link_id || null, raw: j ? null : t.slice(0, 200) };
}, { parent, text });
console.log('응답:', JSON.stringify(res));
if (res.status !== 200 || (res.errors && res.errors.length) || !res.id) {
    console.log('⛔ 게시 실패 — «올렸다»고 적지 않는다.'); process.exit(1);
}

// ── ★검증: 200 은 «게시됨»이 아니다. 스레드를 다시 읽어 실제로 보이는지 본다 ──
await L.wait(4000);
// ★2026-09-27 부모가 «댓글»(t1_)이면 응답에 link 가 없어 댓글 id 로 스레드를 찾다가 total 0 → «안 보인다» 오판(실제로는 게시됨).
//   원글 id 는 부모 댓글의 link_id 로 조회한다.
let linkId = String(res.link || '').replace(/^t3_/, '');
if (!linkId && parent.startsWith('t3_')) linkId = parent.slice(3);
if (!linkId) linkId = await page.evaluate(async (p) => { try { const j = await (await fetch('/api/info.json?id=' + p, { credentials: 'include' })).json(); return String((j.data.children[0] || {}).data?.link_id || '').replace(/^t3_/, ''); } catch { return ''; } }, parent);
if (!linkId) { console.log('⛔ 원글 id 를 못 찾아 검증 불가 — «올렸다»고 적지 않는다'); process.exit(1); }
// ⚠ 응답의 id 는 «t1_ 접두사»가 붙어 오고(t1_pbcxrer), 스레드 JSON 의 id 는 «맨 id»다(pbcxrer).
//   2026-09-22 실측: 이 차이 때문에 검증이 항상 false 로 나와 «안 올라갔다»고 오판했다(실제로는 올라가 있었다).
//   검사기가 «없다»를 말할 때는 검사기부터 의심한다 — 여기서 접두사를 벗겨 맞춘다.
const bareId = String(res.id).replace(/^t1_/, '');
const check = await page.evaluate(async (cfg) => {
    try {
        const r = await fetch(`https://www.reddit.com/comments/${cfg.linkId}/.json?limit=300`, { credentials: 'include' });
        const a = await r.json();
        const out = []; const walk = (n) => { if (!n) return; if (Array.isArray(n)) { n.forEach(walk); return; }
            if (n.kind === 't1' && n.data) { out.push({ id: n.data.id, author: n.data.author, removed: !!n.data.removed_by_category, score: n.data.score }); walk(n.data.replies); }
            else if (n.data && n.data.children) walk(n.data.children); };
        walk(a);
        const mine = out.find((c) => c.id === cfg.id);
        return { total: out.length, found: !!mine, removed: mine ? mine.removed : null, score: mine ? mine.score : null };
    } catch (e) { return { err: String(e.message).slice(0, 80) }; }
}, { linkId, id: bareId });

const permalink = `https://www.reddit.com/comments/${linkId}/comment/${bareId}/`;
console.log('검증:', JSON.stringify(check));
if (!check.found || check.removed) {
    console.log('⛔ 응답은 200 인데 스레드에서 안 보인다(스팸필터 가능성). «올렸다»고 적지 않는다.');
    console.log('   permalink(참고):', permalink); process.exit(1);
}
// ★2026-10-03 익명 시야 검증 — 위의 로그인 검증은 «작성자 시야»라 스팸필터가 지운 댓글도 정상으로 보인다
//   (10/3 r/IndiaInvestments 홍보 스레드: 작성자 목록은 정상인데 쿠키 없는 RSS 에는 내 댓글이 없었다 — 라이브 피드 updated=지금).
//   쿠키 없는 RSS(앱 밖 fetch + 크롬 UA — 레딧 JSON 은 403 이어도 RSS 는 200)로 내 댓글 id 가 보이는지 본다.
//   안 보이면 «게시»가 아니라 «작성자에게만 보임»이다 → 원장 기록 전에 멈춘다. 200 이 아니면(429 등) 판정 불가로 두고 «없다»로 읽지 않는다.
const UA_CHROME = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36';
let anon = false;
for (let i = 1; i <= 3 && anon === false; i++) {
    await L.wait(i === 1 ? 20000 : 45000);
    try {
        const rr = await fetch(`https://www.reddit.com/comments/${linkId}/.rss?limit=300`, { headers: { 'user-agent': UA_CHROME } });
        const xx = await rr.text();
        anon = rr.status === 200 ? (xx.includes('/' + bareId + '/') || xx.includes('t1_' + bareId)) : null;
        console.log(`익명 RSS [${i}] http ${rr.status} · 내 댓글 ${anon === null ? '판정 불가' : anon ? '보임' : '안 보임'}`);
    } catch (e) { anon = null; console.log('익명 RSS 오류:', String(e.message).slice(0, 60)); }
}
if (anon === false) { console.log('⛔ 작성자에게만 보인다 — 레딧 스팸필터가 숨겼을 가능성이 크다. «공개 확인»이 아니다. 원장 기록(pub)을 하지 않는다.'); console.log('   permalink(참고):', permalink); process.exit(1); }
if (anon === null) console.log('⚠ 익명 시야는 판정하지 못했다(RSS 429·오류) — 보고에는 «작성자 시야 정상, 익명 미확인»으로 적는다');
console.log('\n✅ 게시·검증 완료:', permalink);
console.log('다음: node scripts/mkt-plan.js pub reddit "' + permalink + '"');
