// ============================================================================
// «내 종목» 문구 — 한·영·일 (app-view 관례: 파일 안 인라인 객체)
// 원칙: 숫자와 사실만 · 예측·매수/매도 권유 없음 · 영어 칩은 짧게 · 티커·숫자는 자르지 않는다
// 말 고르기(9/29 검토 C): 한국어는 합쇼체 · 동사는 «담기/빼기» · 화면 이름은 탭바처럼 영문(Dashboard·Command·Flow)
//   · 레벨 이름은 앱 용어집(metricGlossary: 콜 월·풋 플로어·맥스 페인·감마 플립)과 같게 · 장외 비중은 첫 등장만 «장외(다크풀)»
//   · 알림은 «닿는 순간·실시간»이라 쓰지 않는다(5분 봉 확정 · 5–15분마다 확인이 사실) · PRO 혜택에 FINRA 장외 비중을 넣지 않는다
// 대표 9/29 «중복 설명하지 마라»: «내 종목»엔 면책·데이터 출처 줄을 두지 않는다 — 면책은 앱 전체(온보딩·대시보드·약관)에 이미 있고,
//   데이터 출처(FINRA 장외 체결 통계)는 앱 약관 «데이터와 책임»에 둔다(AppLegalDocument). 지표의 «뜻»은 짧게 남긴다(ⓘ 지도 읽는 법)
// ============================================================================

import type { WlLocale } from '@/lib/app/watchlistInsights';

export const WL_COPY = {
  ko: {
    myList: '내 종목',
    close: '닫기',
    view: '보기',
    undo: '되돌리기',
    added: '내 종목에 담았습니다',
    removed: '내 종목에서 뺐습니다',
    // 조작·상태 문구(토스트·검색·편집) — 기기 상한 · 저장 실패 · 검색 실패 · 알림 설정 저장 · 개수 · 끌어서 순서 바꾸기 안내
    maxItems: (n: number) => `내 종목은 최대 ${n}종목까지 담을 수 있습니다`,
    saveFail: '기기에 저장하지 못했습니다 · 앱을 닫으면 사라질 수 있습니다',
    removeNotSaved: '기기에 저장하지 못함 · 다시 열면 돌아올 수 있음',
    searchFail: '검색 결과를 불러오지 못했습니다',
    retry: '다시 시도',
    alertSavedHere: '설정은 이 기기에 저장했습니다',
    lpCount: (c: number) => `${c}종목`,
    dnd: {
      role: '순서 변경 가능',
      help: '순서를 바꾸려면 스페이스바를 눌러 집고, 화살표 키로 옮긴 뒤 스페이스바를 다시 눌러 놓습니다. 취소하려면 Esc 키를 누릅니다.',
      start: (t: string, i: number, n: number) => `${t}, 집었습니다. ${n}개 중 ${i}번째입니다.`,
      over: (t: string, i: number, n: number) => `${t}, ${n}개 중 ${i}번째 자리로 옮겼습니다.`,
      out: (t: string) => `${t}, 놓을 수 있는 자리를 벗어났습니다.`,
      end: (t: string, i: number, n: number) => `${t}, ${n}개 중 ${i}번째 자리에 놓았습니다.`,
      cancel: (t: string) => `${t}, 순서 바꾸기를 취소했습니다. 원래 자리로 돌아갔습니다.`,
    },
    eyebrow: 'SIGNUM PRO',
    proLabel: 'PRO 구독',
    per: '/ 월',
    slotPlaceholder: '스토어 현지 가격',
    unavailable: '지금은 구매할 수 없습니다',
    cta: 'PRO 시작하기',
    busy: '처리 중…',
    manage: '기존 종목 정리하기',
    code: '코드 입력',
    later: '나중에',
    codeInApp: '코드는 앱에서 입력할 수 있습니다',
    purchaseFailed: '실패했습니다. 잠시 후 다시 시도해 주세요',
    // 결제 시트·카드는 «제목 + 트리거 한 줄 + 혜택 한 줄씩»만(대표 9/29 — 설명 문장 없이). PRO 도 상한(MAX_ITEMS)이 있다: 숫자는
    //   부르는 쪽이 상수(FREE_LIMIT·MAX_ITEMS)에서 넘긴다
    limitTitle: (n: number) => `무료는 ${n}종목까지`,
    proTrigger: (max: number) => `PRO로 ${max}종목까지`,
    inList: (c: number, n: number) => `지금 담긴 종목 ${c}/${n}`,
    bCapacity: (max: number) => `내 종목 ${max}개`,
    bAlerts: '종목별 포지셔닝 알림',
    // 칩 차등(WATCHLIST_CHIP_TIERING)이 켜졌을 때만 쓴다 — 종류(장외·고래·실적)는 나열하지 않는다(FINRA 장외 비중을 유료 혜택처럼 쓰지 않는다)
    bChips: '행마다 인사이트 칩 2개', bChipsSub: '무료는 행마다 1개',
    bNoAds: '광고 없음',
    alertTitle: '포지셔닝 알림은 PRO',
    alertLede: (t: string | null) => t
      ? [`${t}`, ' 가격이 콜 월·풋 플로어·감마 플립을 넘으면(5분 봉 확정) 숫자와 사실만 푸시로 보냅니다.'] as const
      : ['', '내 종목이 콜 월·풋 플로어·감마 플립을 넘으면(5분 봉 확정) 숫자와 사실만 푸시로 보냅니다.'] as const,
    example: '알림 예시',
    now: '지금',
    aLvl: '콜 월 돌파 · 풋 플로어 이탈 · 감마 플립 교차', aLvlSub: '5분 봉 확정 기준 · 장중 5–15분마다 확인',
    aMp: '만기 주간 맥스 페인 괴리', aMpSub: '만기 3거래일 전부터 · 괴리가 평소보다 클 때',
    aEarn: '실적 D-1 + 내재 변동폭', aEarnSub: '실적 뒤 첫 만기 ATM 스트래들 기준 · 실시간 호가가 있을 때',
    // chips — 칩 차등(WATCHLIST_CHIP_TIERING)이 켜졌을 때만 칩을 PRO 혜택으로 말한다. 꺼지면 칩은 모두에게 같다
    inclHead: '함께', incl: (chips: boolean, max: number) => (chips ? `내 종목 ${max}개 · 행마다 칩 2개 · 광고 없음` : `내 종목 ${max}개 · 광고 없음`),
    chipLockAria: (k: string) => `${k} — PRO 전용`,
    onDevice: '가입 없이 · 이 기기에 저장',
    lpAdd: '내 종목에 담기', lpRemove: '내 종목에서 빼기', lpRemoveSub: '언제든 다시 담을 수 있습니다',
    // 한도보다 많이 가진 목록(PRO 해지·코드 만료)은 «도달»이 아니라 «초과»다
    lpFree: (c: number, n: number) => (c > n ? `${c}/${n} · 무료 한도 초과` : c === n ? `${c}/${n} · 무료 한도 도달` : `${c}/${n} · 무료 한도 내`),
    lpPro: (c: number) => `${c}종목 · PRO`,
    lpFlow: 'Flow 보기', lpFlowSub: '옵션 플로우 · 신규 포지션',
    lpCmd: 'Command 보기', lpCmdSub: '맥스 페인 · 감마 · 장외(다크풀) 비중',
    mapTitle: '지도 읽는 법',
    // 지도 읽는 법(ⓘ) — 지표의 «뜻»만 짧게(대표 9/29 «지표 설명은 적당히 · 중복만 없앤다»)
    mapWalls: '풋 플로어 · 콜 월', mapWallsSub: '지도 양 끝, 현재가 아래·위 20% 안에서 풋·콜 미결제약정이 가장 두꺼운 행사가입니다.',
    mapMp: '맥스 페인', mapMpSub: '만기 때 옵션 매수자 전체의 손실이 가장 큰 가격입니다.',
    mapPx: '가격', mapPxSub: '지금 가격의 자리입니다(장 마감 뒤엔 종가).',
    mapGf: '감마 플립', mapGfSub: '딜러 순감마가 0을 지나는 가격입니다.',
    mapWait: '레벨 갱신 대기', mapWaitSub: '확인되지 않은 레벨은 그리지 않습니다.',
    // «범위 밖» 머리글은 공용 levelOutOfRangeText(Command·Flow 와 같은 글자) — 여기엔 뜻 한 줄만
    mapOutSub: '정해진 범위(벽은 현재가 ±20%, 맥스 페인은 ±35%) 안에 값이 없는 레벨입니다.',
    mapWhale: '고래 칩', mapWhaleSub: '주목 계약 상위 12개에서 새로 늘어난 미결제약정입니다. 콜·풋은 따로 셉니다.',
    levelsWait: '레벨 갱신 대기',
    levelsWaitAria: '옵션 레벨 확인 중 — 검증 전 값은 표시하지 않음',
    levelsDashAria: '가격 없음 — 지도를 그리지 않습니다',
    putFloor: '풋 플로어', callWall: '콜 월', maxPain: '맥스 페인', gammaFlip: '감마 플립',
  },
  en: {
    myList: 'My Watchlist',
    close: 'Close',
    view: 'View',
    undo: 'Undo',
    added: 'Added to My Watchlist',
    removed: 'Removed from My Watchlist',
    maxItems: (n: number) => `My Watchlist holds up to ${n} stocks`,
    saveFail: 'Couldn’t save to this device · it may be lost when the app closes',
    removeNotSaved: 'Not saved on this device · it may come back',
    searchFail: 'Couldn’t load results',
    retry: 'Retry',
    alertSavedHere: 'Settings saved on this device',
    lpCount: (c: number) => `${c} ${c === 1 ? 'stock' : 'stocks'}`,
    dnd: {
      role: 'sortable',
      help: 'To reorder, press Space to pick up a stock, use the arrow keys to move it, then press Space again to drop it. Press Escape to cancel.',
      start: (t: string, i: number, n: number) => `Picked up ${t}. Position ${i} of ${n}.`,
      over: (t: string, i: number, n: number) => `${t} moved to position ${i} of ${n}.`,
      out: (t: string) => `${t} is no longer over a position.`,
      end: (t: string, i: number, n: number) => `${t} dropped at position ${i} of ${n}.`,
      cancel: (t: string) => `Reordering cancelled. ${t} is back in its original position.`,
    },
    eyebrow: 'SIGNUM PRO',
    proLabel: 'PRO',
    per: '/ month',
    slotPlaceholder: 'Local store price',
    unavailable: 'Not available right now',
    cta: 'Start PRO',
    busy: 'Working…',
    manage: 'Tidy up My Watchlist',
    code: 'Redeem code',
    later: 'Not now',
    codeInApp: 'Codes can be redeemed in the app',
    purchaseFailed: 'Something went wrong. Please try again',
    limitTitle: (n: number) => `Free plan: up to ${n} stocks`,
    proTrigger: (max: number) => `Up to ${max} stocks with PRO`,
    inList: (c: number, n: number) => `In My Watchlist ${c}/${n}`,
    bCapacity: (max: number) => `${max}-stock watchlist`,
    bAlerts: 'Positioning alerts per stock',
    bChips: '2 insight chips per row', bChipsSub: 'Free shows 1 per row',
    bNoAds: 'No ads',
    alertTitle: 'Positioning alerts are PRO',
    alertLede: (t: string | null) => t
      ? [`${t}`, ' — when it breaks its call wall, put floor or gamma flip on a confirmed 5-min close, we push the numbers. Nothing else.'] as const
      : ['', 'When your stocks break a call wall, put floor or gamma flip on a confirmed 5-min close, we push the numbers. Nothing else.'] as const,
    example: 'Example',
    now: 'now',
    aLvl: 'Call wall breakout · put floor breakdown · gamma flip crossing', aLvlSub: 'Confirmed on 5-min closes · checked every 5–15 min in session',
    aMp: 'Expiry-week max pain gap', aMpSub: 'From 3 sessions before expiry · when the gap is unusually wide',
    aEarn: 'Earnings D-1 + implied move', aEarnSub: 'ATM straddle of the first expiry after the report · when live quotes exist',
    inclHead: 'Also', incl: (chips: boolean, max: number) => (chips ? `${max}-stock watchlist · 2 chips per row · no ads` : `${max}-stock watchlist · no ads`),
    chipLockAria: (k: string) => `${k} — PRO only`,
    onDevice: 'No sign-up · saved on this device',
    lpAdd: 'Add to My Watchlist', lpRemove: 'Remove from My Watchlist', lpRemoveSub: 'You can add it back anytime',
    lpFree: (c: number, n: number) => (c > n ? `${c}/${n} · over the free limit` : c === n ? `${c}/${n} · free limit reached` : `${c}/${n} · within free limit`),
    lpPro: (c: number) => `${c} ${c === 1 ? 'stock' : 'stocks'} · PRO`,
    lpFlow: 'Open Flow', lpFlowSub: 'Options flow · new positions',
    lpCmd: 'Open Command', lpCmdSub: 'Max pain · gamma · off-exchange (dark pool) share',
    mapTitle: 'Reading the map',
    mapWalls: 'Put floor · call wall', mapWallsSub: 'The two ends: the strikes with the most put / call open interest within 20% below / above price.',
    mapMp: 'Max pain', mapMpSub: 'The price where option buyers as a whole lose the most at expiry.',
    mapPx: 'Price', mapPxSub: 'Where price sits now (the close after hours).',
    mapGf: 'Gamma flip', mapGfSub: 'The price where dealer net gamma crosses zero.',
    mapWait: 'Levels updating', mapWaitSub: 'Unverified levels aren’t drawn.',
    mapOutSub: 'No value within the defined range (walls ±20% of price, max pain ±35%).',
    mapWhale: 'Whale chip', mapWhaleSub: 'New open interest in the top 12 notable contracts — calls and puts counted separately.',
    levelsWait: 'Levels updating',
    levelsWaitAria: 'Checking option levels — unverified values are not shown',
    levelsDashAria: 'No price — map not drawn',
    putFloor: 'Put floor', callWall: 'Call wall', maxPain: 'Max pain', gammaFlip: 'Gamma flip',
  },
  ja: {
    myList: 'マイ銘柄',
    close: '閉じる',
    view: '見る',
    undo: '元に戻す',
    added: 'マイ銘柄に追加しました',
    removed: 'マイ銘柄から外しました',
    maxItems: (n: number) => `マイ銘柄は最大${n}銘柄まで登録できます`,
    saveFail: '端末に保存できませんでした · アプリを閉じると消える場合があります',
    removeNotSaved: '端末に保存できませんでした · 再び表示される場合があります',
    searchFail: '検索結果を読み込めませんでした',
    retry: '再試行',
    alertSavedHere: '設定はこの端末に保存しました',
    lpCount: (c: number) => `${c}銘柄`,
    dnd: {
      role: '並べ替え可能',
      help: '並べ替えるには、スペースキーで銘柄を持ち上げ、矢印キーで移動し、もう一度スペースキーで置きます。取り消すにはEscキーを押します。',
      start: (t: string, i: number, n: number) => `${t}を持ち上げました。${n}件中${i}番目です。`,
      over: (t: string, i: number, n: number) => `${t}を${n}件中${i}番目に移動しました。`,
      out: (t: string) => `${t}は置ける位置から外れました。`,
      end: (t: string, i: number, n: number) => `${t}を${n}件中${i}番目に置きました。`,
      cancel: (t: string) => `並べ替えを取り消しました。${t}は元の位置に戻りました。`,
    },
    eyebrow: 'SIGNUM PRO',
    proLabel: 'PRO',
    per: '/ 月',
    slotPlaceholder: 'ストア現地価格',
    unavailable: '現在購入できません',
    cta: 'PROを始める',
    busy: '処理中…',
    manage: '登録銘柄を整理する',
    code: 'コードを入力',
    later: 'あとで',
    codeInApp: 'コードはアプリで入力できます',
    purchaseFailed: '失敗しました。しばらくしてからお試しください',
    limitTitle: (n: number) => `無料は${n}銘柄まで`,
    proTrigger: (max: number) => `PROなら${max}銘柄まで`,
    inList: (c: number, n: number) => `登録中 ${c}/${n}`,
    bCapacity: (max: number) => `マイ銘柄${max}銘柄`,
    bAlerts: '銘柄別ポジショニング通知',
    bChips: '1行にインサイトチップ2つ', bChipsSub: '無料は1行に1つ',
    bNoAds: '広告なし',
    alertTitle: 'ポジショニング通知はPRO',
    alertLede: (t: string | null) => t
      ? [`${t}`, 'の価格がコールウォール・プットフロア・ガンマフリップを抜けたら（5分足確定）、数字と事実だけをプッシュで届けます。'] as const
      : ['', 'マイ銘柄がコールウォール・プットフロア・ガンマフリップを抜けたら（5分足確定）、数字と事実だけをプッシュで届けます。'] as const,
    example: '通知の例',
    now: '今',
    aLvl: 'コールウォール突破・プットフロア割れ・ガンマフリップ交差', aLvlSub: '5分足確定ベース · 取引中5–15分ごとに確認',
    aMp: '満期週のマックスペイン乖離', aMpSub: '満期3営業日前から · 乖離が平常より大きいとき',
    aEarn: '決算 D-1 + 想定変動幅', aEarnSub: '決算後最初の満期のATMストラドル基準 · リアルタイム気配があるとき',
    inclHead: 'あわせて', incl: (chips: boolean, max: number) => (chips ? `マイ銘柄${max}銘柄 · 1行にチップ2つ · 広告なし` : `マイ銘柄${max}銘柄 · 広告なし`),
    chipLockAria: (k: string) => `${k} — PRO専用`,
    onDevice: '登録不要 · この端末に保存',
    lpAdd: 'マイ銘柄に追加', lpRemove: 'マイ銘柄から外す', lpRemoveSub: 'いつでも追加し直せます',
    lpFree: (c: number, n: number) => (c > n ? `${c}/${n} · 無料枠を超過` : c === n ? `${c}/${n} · 無料枠に到達` : `${c}/${n} · 無料枠内`),
    lpPro: (c: number) => `${c}銘柄 · PRO`,
    lpFlow: 'Flowを見る', lpFlowSub: 'オプションフロー · 新規ポジション',
    lpCmd: 'Commandを見る', lpCmdSub: 'マックスペイン · ガンマ · 場外（ダークプール）比率',
    mapTitle: 'マップの見方',
    mapWalls: 'プットフロア · コールウォール', mapWallsSub: 'マップの両端。現在値の下・上20%以内で、プット・コールの建玉が最も厚い行使価格です。',
    mapMp: 'マックスペイン', mapMpSub: '満期時にオプション買い手全体の損失が最大になる価格です。',
    mapPx: '価格', mapPxSub: '現在値の位置です（引け後は終値）。',
    mapGf: 'ガンマフリップ', mapGfSub: 'ディーラーの純ガンマがゼロを横切る価格です。',
    mapWait: 'レベル更新待ち', mapWaitSub: '確認できていないレベルは表示しません。',
    mapOutSub: '決められた範囲（ウォールは現在値±20%、マックスペインは±35%）内に値がないレベルです。',
    mapWhale: '大口チップ', mapWhaleSub: '注目契約上位12件で新たに増えた建玉です。コール・プットは別々に数えます。',
    levelsWait: 'レベル更新待ち',
    levelsWaitAria: 'オプションレベル確認中 — 未検証の値は表示しません',
    levelsDashAria: '価格なし — マップは表示しません',
    putFloor: 'プットフロア', callWall: 'コールウォール', maxPain: 'マックスペイン', gammaFlip: 'ガンマフリップ',
  },
} as const;

export type WlCopy = (typeof WL_COPY)['ko'] | (typeof WL_COPY)['en'] | (typeof WL_COPY)['ja'];
export const wlCopy = (loc: WlLocale): WlCopy => WL_COPY[loc];
