// ============================================================================
// «내 종목» 문구 — 한·영·일 (app-view 관례: 파일 안 인라인 객체)
// 원칙: 숫자와 사실만 · 예측·매수/매도 권유 없음 · 영어 칩은 짧게 · 티커·숫자는 자르지 않는다
// ============================================================================

import type { WlLocale } from '@/lib/app/watchlistInsights';

export const WL_COPY = {
  ko: {
    myList: '내 종목',
    close: '닫기',
    view: '보기',
    undo: '되돌리기',
    added: '내 종목에 추가',
    removed: '내 종목에서 뺐습니다',
    firstTip: '내 종목은 대시보드 맨 위와 칩 줄 맨 앞에 모입니다',
    eyebrow: 'SIGNUM PRO',
    proLabel: 'PRO 구독',
    per: '/ 월',
    slotPlaceholder: '스토어 현지 가격',
    unavailable: '지금은 구매할 수 없습니다',
    cta: 'PRO 시작하기',
    busy: '처리 중…',
    manage: '기존 종목 정리하기',
    code: '코드 입력',
    later: '나중에',
    codeInApp: '코드는 앱에서 입력할 수 있습니다',
    purchaseFailed: '실패했습니다. 잠시 후 다시 시도해 주세요',
    limitTitle: (n: number) => `무료는 ${n}종목까지`,
    limitLede: (t: string) => ['', t, '도 담으려면 한 종목을 빼거나, PRO로 제한 없이 담으세요.'] as const,
    inList: (c: number, n: number) => `지금 담긴 종목 ${c}/${n}`,
    bUnlimited: '내 종목 무제한', bUnlimitedSub: (n: number) => `무료는 ${n}종목까지`,
    bAlerts: '종목별 실시간 포지셔닝 알림', bAlertsSub: '콜월 돌파 · 풋플로어 이탈 · 감마 플립 교차 외 4종',
    bChips: '모든 인사이트 칩', bChipsSub: '행마다 2개 · 장외 비중 · 고래 신규 포지션 · 실적 일정',
    bNoAds: '광고 없음', bNoAdsSub: '배너·전면 광고 전부 제거',
    alertTitle: '실시간 포지셔닝 알림은 PRO',
    alertLede: (t: string | null) => t
      ? [`${t}`, ' 가격이 콜월·풋플로어·감마 플립에 닿는 순간, 숫자와 사실만 푸시로 보냅니다.'] as const
      : ['', '내 종목이 콜월·풋플로어·감마 플립에 닿는 순간, 숫자와 사실만 푸시로 보냅니다.'] as const,
    example: '알림 예시',
    now: '지금',
    aLvl: '콜월 돌파 · 풋플로어 이탈 · 감마 플립 교차', aLvlSub: '5분 봉 확정 기준 · 장중 5–15분마다 확인',
    aMp: '만기 주간 맥스페인 괴리', aMpSub: '만기 3거래일 전부터 · 괴리가 평소보다 클 때',
    aDp: '장외(다크풀) 비중 급변', aDpSub: 'FINRA 일간 · 20일 평균 대비 · 장 마감 후 1회',
    aEarn: '실적 D-1 + 옵션 내재 변동', aEarnSub: '실적 뒤 첫 만기 ATM 스트래들 기준 · 실시간 호가가 있을 때',
    // chips — 칩 차등(WATCHLIST_CHIP_TIERING)이 켜졌을 때만 칩을 PRO 혜택으로 말한다. 꺼지면 칩은 모두에게 같다
    inclHead: '함께', incl: (chips: boolean) => (chips ? '내 종목 무제한 · 모든 인사이트 칩 · 광고 없음' : '내 종목 무제한 · 광고 없음'),
    genTitle: '내 종목, 제한 없이',
    genLede: (n: number, chips: boolean) => (chips
      ? `무료는 ${n}종목 · 행마다 칩 1개까지입니다. PRO는 제한 없이 담고 행마다 칩 2개를 봅니다.`
      : `무료는 ${n}종목까지입니다. PRO는 제한 없이 담고 광고 없이 봅니다.`),
    chipLockAria: (k: string) => `${k} — PRO 전용`,
    onDevice: '가입 없이 · 이 폰에 저장',
    lpAdd: '내 종목에 추가', lpRemove: '내 종목에서 빼기', lpRemoveSub: '언제든 다시 담을 수 있습니다',
    lpFree: (c: number, n: number) => (c >= n ? `${c}/${n} · 무료 한도 도달` : `${c}/${n} · 무료 한도 안`),
    lpPro: (c: number) => `${c}종목 · PRO`,
    lpFlow: '플로우 보기', lpFlowSub: '옵션 흐름 · 신규 포지션',
    lpCmd: '커맨드 보기', lpCmdSub: '맥스페인 · 감마 · 다크풀',
    mapTitle: '지도 읽는 법',
    mapWalls: '풋플로어 · 콜월', mapWallsSub: '왼쪽 끝은 풋 미결제약정이 가장 두꺼운 행사가(현재가 아래 20% 안), 오른쪽 끝은 콜 쪽(현재가 위 20% 안)입니다.',
    mapMp: '맥스페인', mapMpSub: '만기 때 옵션 매수자 전체의 손실이 가장 큰 가격입니다. 금색은 이 표식과 ★에만 씁니다.',
    mapPx: '가격', mapPxSub: '그 범위 안에서 지금(장 마감 뒤엔 종가) 자리입니다.',
    mapWait: '레벨 갱신 대기', mapWaitSub: '레벨이 정의를 벗어났거나 오래됐으면 숫자를 지어내지 않고 지도를 숨깁니다.',
    mapSrc: '옵션 레벨: 옵션 체인 EOD · 장외 비중: Data source: FINRA · 숫자와 사실만 보여 줍니다 · 투자 권유가 아닙니다',
    levelsWait: '레벨 갱신 대기',
    levelsWaitAria: '옵션 레벨 확인 중 — 검증 전 값은 표시하지 않음',
    putFloor: '풋플로어', callWall: '콜월', maxPain: '맥스페인', gammaFlip: '감마 플립',
  },
  en: {
    myList: 'My Watchlist',
    close: 'Close',
    view: 'View',
    undo: 'Undo',
    added: 'Added to My Watchlist',
    removed: 'Removed from My Watchlist',
    firstTip: 'Starred stocks gather at the top of the Dashboard and the front of the ticker chips',
    eyebrow: 'SIGNUM PRO',
    proLabel: 'PRO',
    per: '/ month',
    slotPlaceholder: 'Local store price',
    unavailable: 'Not available right now',
    cta: 'Start PRO',
    busy: 'Working…',
    manage: 'Tidy up my list',
    code: 'Redeem code',
    later: 'Not now',
    codeInApp: 'Codes can be redeemed in the app',
    purchaseFailed: 'Something went wrong. Please try again',
    limitTitle: (n: number) => `Free covers ${n} stocks`,
    limitLede: (t: string) => ['To add ', t, ', remove one — or go PRO for no limit.'] as const,
    inList: (c: number, n: number) => `In your list ${c}/${n}`,
    bUnlimited: 'Unlimited watchlist', bUnlimitedSub: (n: number) => `Free covers ${n} stocks`,
    bAlerts: 'Real-time positioning alerts', bAlertsSub: 'Call wall · put floor · gamma flip + 4 more',
    bChips: 'Every insight chip', bChipsSub: '2 per row · off-exchange · whale positions · earnings dates',
    bNoAds: 'No ads', bNoAdsSub: 'Every banner and interstitial removed',
    alertTitle: 'Real-time positioning alerts are PRO',
    alertLede: (t: string | null) => t
      ? [`${t}`, ' — the moment it touches its call wall, put floor or gamma flip, we push the numbers. Nothing else.'] as const
      : ['', 'The moment your stocks touch a call wall, put floor or gamma flip, we push the numbers. Nothing else.'] as const,
    example: 'Example',
    now: 'now',
    aLvl: 'Call wall · put floor · gamma flip crosses', aLvlSub: 'Confirmed on 5-min closes · checked every 5–15 min',
    aMp: 'Expiry-week max-pain gap', aMpSub: 'From 3 sessions before expiry · when the gap is unusually wide',
    aDp: 'Off-exchange (dark pool) spikes', aDpSub: 'FINRA daily · vs 20-day average · once after close',
    aEarn: 'Earnings D-1 + implied move', aEarnSub: 'ATM straddle of the first expiry after the report · when live quotes exist',
    inclHead: 'Also', incl: (chips: boolean) => (chips ? 'Unlimited watchlist · every insight chip · no ads' : 'Unlimited watchlist · no ads'),
    genTitle: 'Your watchlist, unlimited',
    genLede: (n: number, chips: boolean) => (chips
      ? `Free covers ${n} stocks and 1 chip per row. PRO removes the cap and shows 2 chips per row.`
      : `Free covers ${n} stocks. PRO removes the cap and the ads.`),
    chipLockAria: (k: string) => `${k} — PRO only`,
    onDevice: 'No sign-up · Saved on this phone',
    lpAdd: 'Add to My Watchlist', lpRemove: 'Remove from My Watchlist', lpRemoveSub: 'You can add it back anytime',
    lpFree: (c: number, n: number) => (c >= n ? `${c}/${n} · free limit reached` : `${c}/${n} · within free limit`),
    lpPro: (c: number) => `${c} stocks · PRO`,
    lpFlow: 'Open Flow', lpFlowSub: 'Options flow · new positions',
    lpCmd: 'Open Command', lpCmdSub: 'Max pain · gamma · dark pool',
    mapTitle: 'Reading the map',
    mapWalls: 'Put floor · call wall', mapWallsSub: 'Left end: the strike with the heaviest put open interest within 20% below price. Right end: the same for calls within 20% above.',
    mapMp: 'Max pain', mapMpSub: 'The price where option buyers as a whole lose the most at expiry. Gold is used only for this mark and ★.',
    mapPx: 'Price', mapPxSub: 'Where the price sits inside that range now (the close after hours).',
    mapWait: 'Levels updating', mapWaitSub: 'If a level breaks its definition or goes stale, we hide the map instead of inventing numbers.',
    mapSrc: 'Option levels: options chain EOD · Off-exchange: Data source: FINRA · Numbers and facts only · Not investment advice',
    levelsWait: 'Levels updating',
    levelsWaitAria: 'Checking option levels — unverified values are not shown',
    putFloor: 'Put floor', callWall: 'Call wall', maxPain: 'Max pain', gammaFlip: 'Gamma flip',
  },
  ja: {
    myList: 'マイ銘柄',
    close: '閉じる',
    view: '見る',
    undo: '元に戻す',
    added: 'マイ銘柄に追加',
    removed: 'マイ銘柄から外しました',
    firstTip: 'マイ銘柄はダッシュボード上部とチップ列の先頭に集まります',
    eyebrow: 'SIGNUM PRO',
    proLabel: 'PRO',
    per: '/ 月',
    slotPlaceholder: 'ストア現地価格',
    unavailable: '現在購入できません',
    cta: 'PROを始める',
    busy: '処理中…',
    manage: '登録銘柄を整理する',
    code: 'コードを入力',
    later: 'あとで',
    codeInApp: 'コードはアプリで入力できます',
    purchaseFailed: '失敗しました。しばらくしてからお試しください',
    limitTitle: (n: number) => `無料は${n}銘柄まで`,
    limitLede: (t: string) => ['', t, 'を追加するには1銘柄外すか、PROで上限なしに追加できます。'] as const,
    inList: (c: number, n: number) => `登録中 ${c}/${n}`,
    bUnlimited: 'マイ銘柄 上限なし', bUnlimitedSub: (n: number) => `無料は${n}銘柄まで`,
    bAlerts: '銘柄別リアルタイム・ポジショニング通知', bAlertsSub: 'コールウォール突破・プットフロア割れ・ガンマフリップ交差 ほか4種',
    bChips: 'すべてのインサイトチップ', bChipsSub: '1行に2つ · 場外比率 · 大口新規 · 決算日程',
    bNoAds: '広告なし', bNoAdsSub: 'バナー・全画面広告をすべて非表示',
    alertTitle: 'リアルタイム・ポジショニング通知はPRO',
    alertLede: (t: string | null) => t
      ? [`${t}`, 'の価格がコールウォール・プットフロア・ガンマフリップに触れた瞬間、数字と事実だけをプッシュで届けます。'] as const
      : ['', 'マイ銘柄がコールウォール・プットフロア・ガンマフリップに触れた瞬間、数字と事実だけをプッシュで届けます。'] as const,
    example: '通知の例',
    now: '今',
    aLvl: 'コールウォール突破・プットフロア割れ・ガンマフリップ交差', aLvlSub: '5分足確定ベース · 取引中5–15分ごとに確認',
    aMp: '満期週のマックスペイン乖離', aMpSub: '満期3営業日前から · 乖離が平常より大きいとき',
    aDp: '場外(ダークプール)比率の急変', aDpSub: 'FINRA日次 · 20日平均比 · 引け後1回',
    aEarn: '決算 D-1 + 織り込み変動', aEarnSub: '決算後最初の満期のATMストラドル基準 · リアルタイム気配があるとき',
    inclHead: 'あわせて', incl: (chips: boolean) => (chips ? 'マイ銘柄上限なし · すべてのチップ · 広告なし' : 'マイ銘柄上限なし · 広告なし'),
    genTitle: 'マイ銘柄を上限なしで',
    genLede: (n: number, chips: boolean) => (chips
      ? `無料は${n}銘柄・1行にチップ1つまで。PROは上限なしで、1行にチップ2つを表示します。`
      : `無料は${n}銘柄まで。PROは上限なしで、広告なしで表示します。`),
    chipLockAria: (k: string) => `${k} — PRO専用`,
    onDevice: '登録不要 · この端末に保存',
    lpAdd: 'マイ銘柄に追加', lpRemove: 'マイ銘柄から外す', lpRemoveSub: 'いつでも追加し直せます',
    lpFree: (c: number, n: number) => (c >= n ? `${c}/${n} · 無料枠に到達` : `${c}/${n} · 無料枠内`),
    lpPro: (c: number) => `${c}銘柄 · PRO`,
    lpFlow: 'フローを見る', lpFlowSub: 'オプションフロー · 新規ポジション',
    lpCmd: 'コマンドを見る', lpCmdSub: 'マックスペイン · ガンマ · ダークプール',
    mapTitle: 'マップの見方',
    mapWalls: 'プットフロア · コールウォール', mapWallsSub: '左端は現在値の下20%以内でプット建玉が最も厚い行使価格、右端は上20%以内のコール側です。',
    mapMp: 'マックスペイン', mapMpSub: '満期時にオプション買い手全体の損失が最大になる価格です。金色はこの印と★だけに使います。',
    mapPx: '価格', mapPxSub: 'その範囲の中の現在位置(引け後は終値)です。',
    mapWait: 'レベル更新待ち', mapWaitSub: 'レベルが定義から外れたり古くなったりしたら、数字を作らずマップを隠します。',
    mapSrc: 'オプションレベル: オプションチェーンEOD · 場外比率: Data source: FINRA · 数字と事実だけ · 投資勧誘ではありません',
    levelsWait: 'レベル更新待ち',
    levelsWaitAria: 'オプションレベル確認中 — 未検証の値は表示しません',
    putFloor: 'プットフロア', callWall: 'コールウォール', maxPain: 'マックスペイン', gammaFlip: 'ガンマフリップ',
  },
} as const;

export type WlCopy = (typeof WL_COPY)['ko'] | (typeof WL_COPY)['en'] | (typeof WL_COPY)['ja'];
export const wlCopy = (loc: WlLocale): WlCopy => WL_COPY[loc];
