// ============================================================================
// 종목 이름(한·영·일) — «내 종목» 행·시트의 이름 줄
// ----------------------------------------------------------------------------
// 배치 API 에는 회사명이 없다. 회사명은 바뀌지 않으므로 자주 담는 종목은 여기 적어 둔다
// (실적 브리프 크론의 NAME_KO/NAME_JA 와 같은 표기 — «지어내게» 두지 않는다).
// 여기 없는 종목은 실적 캘린더 브리프의 이름을 쓰고, 그것도 없으면 이름 줄을 비운다.
// ============================================================================

import type { WlLocale } from '@/lib/app/watchlistInsights';

type N = [ko: string, en: string, ja: string];

const NAMES: Record<string, N> = {
  AAPL: ['애플', 'Apple', 'アップル'],
  MSFT: ['마이크로소프트', 'Microsoft', 'マイクロソフト'],
  GOOGL: ['알파벳', 'Alphabet', 'アルファベット'],
  GOOG: ['알파벳', 'Alphabet', 'アルファベット'],
  AMZN: ['아마존', 'Amazon', 'アマゾン'],
  META: ['메타', 'Meta Platforms', 'メタ'],
  NVDA: ['엔비디아', 'NVIDIA', 'エヌビディア'],
  TSLA: ['테슬라', 'Tesla', 'テスラ'],
  AVGO: ['브로드컴', 'Broadcom', 'ブロードコム'],
  ORCL: ['오라클', 'Oracle', 'オラクル'],
  CRM: ['세일즈포스', 'Salesforce', 'セールスフォース'],
  AMD: ['AMD', 'AMD', 'AMD'],
  INTC: ['인텔', 'Intel', 'インテル'],
  MU: ['마이크론', 'Micron', 'マイクロン'],
  TSM: ['TSMC', 'TSMC', 'TSMC'],
  ASML: ['ASML', 'ASML', 'ASML'],
  ARM: ['ARM', 'Arm Holdings', 'アーム'],
  QCOM: ['퀄컴', 'Qualcomm', 'クアルコム'],
  TXN: ['텍사스인스트루먼트', 'Texas Instruments', 'テキサス・インスツルメンツ'],
  MRVL: ['마벨', 'Marvell', 'マーベル'],
  SMCI: ['슈퍼마이크로', 'Supermicro', 'スーパーマイクロ'],
  AMAT: ['어플라이드', 'Applied Materials', 'アプライド'],
  LRCX: ['램리서치', 'Lam Research', 'ラムリサーチ'],
  KLAC: ['KLA', 'KLA', 'KLA'],
  ADBE: ['어도비', 'Adobe', 'アドビ'],
  NOW: ['서비스나우', 'ServiceNow', 'サービスナウ'],
  NFLX: ['넷플릭스', 'Netflix', 'ネットフリックス'],
  PLTR: ['팔란티어', 'Palantir', 'パランティア'],
  SNOW: ['스노우플레이크', 'Snowflake', 'スノーフレーク'],
  DDOG: ['데이터독', 'Datadog', 'データドッグ'],
  CRWD: ['크라우드스트라이크', 'CrowdStrike', 'クラウドストライク'],
  PANW: ['팔로알토', 'Palo Alto Networks', 'パロアルト'],
  FTNT: ['포티넷', 'Fortinet', 'フォーティネット'],
  ZS: ['지스케일러', 'Zscaler', 'ゼットスケーラー'],
  NET: ['클라우드플레어', 'Cloudflare', 'クラウドフレア'],
  MDB: ['몽고DB', 'MongoDB', 'MongoDB'],
  SHOP: ['쇼피파이', 'Shopify', 'ショッピファイ'],
  UBER: ['우버', 'Uber', 'ウーバー'],
  ABNB: ['에어비앤비', 'Airbnb', 'エアビーアンドビー'],
  DIS: ['디즈니', 'Disney', 'ディズニー'],
  SPOT: ['스포티파이', 'Spotify', 'スポティファイ'],
  RBLX: ['로블록스', 'Roblox', 'ロブロックス'],
  COIN: ['코인베이스', 'Coinbase', 'コインベース'],
  HOOD: ['로빈후드', 'Robinhood', 'ロビンフッド'],
  PYPL: ['페이팔', 'PayPal', 'ペイパル'],
  XYZ: ['블록', 'Block', 'ブロック'],
  SOFI: ['소파이', 'SoFi', 'ソーファイ'],
  AFRM: ['어펌', 'Affirm', 'アファーム'],
  UPST: ['업스타트', 'Upstart', 'アップスタート'],
  MSTR: ['스트래티지', 'Strategy', 'ストラテジー'],
  DELL: ['델', 'Dell', 'デル'],
  IONQ: ['아이온큐', 'IonQ', 'イオンキュー'],
  RKLB: ['로켓랩', 'Rocket Lab', 'ロケット・ラボ'],
  ASTS: ['AST 스페이스모바일', 'AST SpaceMobile', 'ASTスペースモバイル'],
  SMR: ['뉴스케일', 'NuScale', 'ニュースケール'],
  OKLO: ['오클로', 'Oklo', 'オクロ'],
  CEG: ['컨스텔레이션', 'Constellation Energy', 'コンステレーション'],
  VST: ['비스트라', 'Vistra', 'ビストラ'],
  NEE: ['넥스트에라', 'NextEra Energy', 'ネクステラ'],
  GEV: ['GE 버노바', 'GE Vernova', 'GEベルノバ'],
  JPM: ['JP모간', 'JPMorgan Chase', 'JPモルガン'],
  BAC: ['뱅크오브아메리카', 'Bank of America', 'バンク・オブ・アメリカ'],
  WFC: ['웰스파고', 'Wells Fargo', 'ウェルズ・ファーゴ'],
  GS: ['골드만삭스', 'Goldman Sachs', 'ゴールドマン・サックス'],
  MS: ['모간스탠리', 'Morgan Stanley', 'モルガン・スタンレー'],
  C: ['씨티그룹', 'Citigroup', 'シティグループ'],
  BLK: ['블랙록', 'BlackRock', 'ブラックロック'],
  V: ['비자', 'Visa', 'ビザ'],
  MA: ['마스터카드', 'Mastercard', 'マスターカード'],
  'BRK.B': ['버크셔', 'Berkshire Hathaway', 'バークシャー'],
  JNJ: ['존슨앤드존슨', 'Johnson & Johnson', 'ジョンソン・エンド・ジョンソン'],
  LLY: ['일라이릴리', 'Eli Lilly', 'イーライリリー'],
  PFE: ['화이자', 'Pfizer', 'ファイザー'],
  MRK: ['머크', 'Merck', 'メルク'],
  ABBV: ['애브비', 'AbbVie', 'アッヴィ'],
  UNH: ['유나이티드헬스', 'UnitedHealth', 'ユナイテッドヘルス'],
  AMGN: ['암젠', 'Amgen', 'アムジェン'],
  GILD: ['길리어드', 'Gilead', 'ギリアド'],
  NVO: ['노보노디스크', 'Novo Nordisk', 'ノボノルディスク'],
  VRTX: ['버텍스', 'Vertex', 'バーテックス'],
  REGN: ['리제네론', 'Regeneron', 'リジェネロン'],
  ISRG: ['인튜이티브서지컬', 'Intuitive Surgical', 'インテュイティブ'],
  WMT: ['월마트', 'Walmart', 'ウォルマート'],
  COST: ['코스트코', 'Costco', 'コストコ'],
  HD: ['홈디포', 'Home Depot', 'ホーム・デポ'],
  NKE: ['나이키', 'Nike', 'ナイキ'],
  MCD: ['맥도날드', "McDonald's", 'マクドナルド'],
  SBUX: ['스타벅스', 'Starbucks', 'スターバックス'],
  PEP: ['펩시코', 'PepsiCo', 'ペプシコ'],
  KO: ['코카콜라', 'Coca-Cola', 'コカ・コーラ'],
  PG: ['P&G', 'Procter & Gamble', 'P&G'],
  TGT: ['타깃', 'Target', 'ターゲット'],
  LULU: ['룰루레몬', 'Lululemon', 'ルルレモン'],
  XOM: ['엑슨모빌', 'Exxon Mobil', 'エクソンモービル'],
  CVX: ['셰브론', 'Chevron', 'シェブロン'],
  OXY: ['옥시덴탈', 'Occidental', 'オキシデンタル'],
  CAT: ['캐터필러', 'Caterpillar', 'キャタピラー'],
  BA: ['보잉', 'Boeing', 'ボーイング'],
  GE: ['GE 에어로스페이스', 'GE Aerospace', 'GEエアロスペース'],
  LMT: ['록히드마틴', 'Lockheed Martin', 'ロッキード・マーチン'],
  RTX: ['RTX', 'RTX', 'RTX'],
  UPS: ['UPS', 'UPS', 'UPS'],
  HON: ['허니웰', 'Honeywell', 'ハネウェル'],
  DE: ['디어', 'Deere', 'ディア'],
  SPY: ['S&P 500 ETF', 'S&P 500 ETF', 'S&P500 ETF'],
  QQQ: ['나스닥 100 ETF', 'Nasdaq-100 ETF', 'ナスダック100 ETF'],
  IWM: ['러셀 2000 ETF', 'Russell 2000 ETF', 'ラッセル2000 ETF'],
  DIA: ['다우 ETF', 'Dow ETF', 'ダウ ETF'],
  SOXX: ['반도체 ETF', 'Semiconductor ETF', '半導体 ETF'],
  SMH: ['반도체 ETF', 'Semiconductor ETF', '半導体 ETF'],
  TQQQ: ['나스닥 3배 ETF', 'Nasdaq 3x ETF', 'ナスダック3倍 ETF'],
  SOXL: ['반도체 3배 ETF', 'Semis 3x ETF', '半導体3倍 ETF'],
  GLD: ['금 ETF', 'Gold ETF', '金 ETF'],
  TLT: ['미 장기채 ETF', '20Y+ Treasury ETF', '米長期債 ETF'],
};

/** 이름(없으면 fallback, 그것도 없으면 빈 문자열) */
export function tickerName(t: string, loc: WlLocale, fallback?: string | null): string {
  const row = NAMES[(t || '').toUpperCase()];
  if (row) return loc === 'ko' ? row[0] : loc === 'ja' ? row[2] : row[1];
  return (fallback || '').trim();
}
