/**
 * GET /api/guardian/briefing?locale=ko
 * 
 * Returns the latest AI morning briefing from Redis.
 * Supports per-locale briefings (ko/en/ja).
 * Generated by EC2 Worker at 08:00 ET via Gemini AI.
 */

import { NextResponse, NextRequest } from 'next/server';
import { getFromCache } from '@/services/redisClient';

export async function GET(req: NextRequest) {
    try {
        const locale = req.nextUrl.searchParams.get('locale') || 'ko';

        // Today's date in ET (briefing is only valid for the current trading day)
        const todayET = new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
        // Also accept US format (M/D/YYYY) since generate stores in en-US format
        const todayUS = new Date().toLocaleDateString('en-US', { timeZone: 'America/New_York' });

        // Try locale-specific key first (V8.0 format)
        const localeKey = `guardian:morning_briefing:${locale}`;
        const localeBriefing = await getFromCache<any>(localeKey);

        if (localeBriefing) {
            // Check if briefing is from today (skip stale data)
            const briefingDate = localeBriefing.date || '';
            const isToday = briefingDate === todayET || briefingDate === todayUS;

            if (isToday) {
                return NextResponse.json({
                    success: true,
                    briefing: localeBriefing.briefing,
                    date: localeBriefing.date,
                    source: localeBriefing.source,
                    generatedAt: localeBriefing.generatedAt,
                    newsCount: localeBriefing.newsCount || 0,
                    calendarCount: localeBriefing.calendarCount || 0,
                });
            }
            // Stale briefing — fall through to "no briefing" response
        }

        // Fallback to legacy key (backward compat)
        const legacyKey = 'guardian:morning_briefing';
        const legacyBriefing = await getFromCache<any>(legacyKey);

        if (legacyBriefing) {
            const briefingDate = legacyBriefing.date || '';
            const isToday = briefingDate === todayET || briefingDate === todayUS;

            if (isToday) {
                return NextResponse.json({
                    success: true,
                    briefing: legacyBriefing.text || legacyBriefing.briefing,
                    date: legacyBriefing.date,
                    source: legacyBriefing.source,
                    generatedAt: legacyBriefing.generatedAt,
                    preMarket: legacyBriefing.preMarket,
                });
            }
        }

        return NextResponse.json({
            success: true,
            briefing: null,
            message: 'No briefing available yet. Generated daily at 08:00 ET.',
        });

    } catch (error: any) {
        console.error('[Guardian Briefing API]', error.message);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
