/**
 * GET /api/guardian/briefing
 * 
 * Returns the latest AI morning briefing from Redis (generated by EC2 Worker at 08:00 ET).
 * If no briefing exists, returns a template-based fallback.
 */

import { NextResponse } from 'next/server';
import { getFromCache } from '@/services/redisClient';

const BRIEFING_KEY = 'guardian:morning_briefing';

export async function GET() {
    try {
        const briefing = await getFromCache<any>(BRIEFING_KEY);

        if (briefing) {
            return NextResponse.json({
                success: true,
                briefing: briefing.text,
                date: briefing.date,
                source: briefing.source,
                generatedAt: briefing.generatedAt,
                preMarket: briefing.preMarket,
            });
        }

        return NextResponse.json({
            success: true,
            briefing: null,
            message: 'No briefing available yet. Generated daily at 08:00 ET.',
        });

    } catch (error: any) {
        console.error('[Guardian Briefing API]', error.message);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
