/**
 * GET /api/guardian/briefing?locale=ko
 * 
 * Returns the latest AI morning briefing from Redis.
 * Supports per-locale briefings (ko/en/ja).
 * Generated by EC2 Worker at 08:00 ET via Gemini AI.
 */

import { NextResponse, NextRequest } from 'next/server';
import { getFromCache } from '@/services/redisClient';

export async function GET(req: NextRequest) {
    try {
        const locale = req.nextUrl.searchParams.get('locale') || 'ko';

        // Try locale-specific key first (V8.0 format)
        const localeKey = `guardian:morning_briefing:${locale}`;
        const localeBriefing = await getFromCache<any>(localeKey);

        if (localeBriefing) {
            return NextResponse.json({
                success: true,
                briefing: localeBriefing.briefing,
                date: localeBriefing.date,
                source: localeBriefing.source,
                generatedAt: localeBriefing.generatedAt,
                newsCount: localeBriefing.newsCount || 0,
                calendarCount: localeBriefing.calendarCount || 0,
            });
        }

        // Fallback to legacy key (backward compat)
        const legacyKey = 'guardian:morning_briefing';
        const legacyBriefing = await getFromCache<any>(legacyKey);

        if (legacyBriefing) {
            return NextResponse.json({
                success: true,
                briefing: legacyBriefing.text || legacyBriefing.briefing,
                date: legacyBriefing.date,
                source: legacyBriefing.source,
                generatedAt: legacyBriefing.generatedAt,
                preMarket: legacyBriefing.preMarket,
            });
        }

        return NextResponse.json({
            success: true,
            briefing: null,
            message: 'No briefing available yet. Generated daily at 08:00 ET.',
        });

    } catch (error: any) {
        console.error('[Guardian Briefing API]', error.message);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
